// Copyright 2026 The kardinal-promoter Authors.
// Licensed under the Apache License, Version 2.0

package scm_test

import (
	"fmt"
	"runtime"
	"strings"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	v1alpha1 "github.com/kardinal-promoter/kardinal-promoter/api/v1alpha1"
	"github.com/kardinal-promoter/kardinal-promoter/pkg/scm"
)

// prTemplateBody is the default body data the pr template tests render for.
func prTemplateBody() scm.PRBody {
	at := metav1.NewTime(time.Date(2026, 3, 4, 5, 6, 0, 0, time.UTC))
	return scm.PRBody{
		PipelineName: "web", Environment: "prod", BundleName: "web-v2",
		Bundle: v1alpha1.BundleSpec{Type: "image",
			Images:     []v1alpha1.ImageRef{{Repository: "ghcr.io/acme/web", Tag: "2.0.0"}},
			Provenance: &v1alpha1.BundleProvenance{Author: "octocat", CommitSHA: "abcdef0123456789", CIRunURL: "https://ci.example/1"}},
		GateResults:          []v1alpha1.GateResult{{GateName: "soak", Result: "Pass", Reason: "a || b", EvaluatedAt: at}},
		UpstreamEnvironments: []scm.PRBodyUpstreamEnv{{Name: "uat", HealthCheckedAt: &at, Elapsed: "30m"}},
	}
}

// TestRenderPR_Defaults: without a pr config, or with an empty one, the PR
// keeps the default title, body and labels.
func TestRenderPR_Defaults(t *testing.T) {
	body := prTemplateBody()
	want, err := scm.RenderPRBody(body)
	require.NoError(t, err)
	for name, cfg := range map[string]*v1alpha1.PRConfig{"nil": nil, "empty": {}} {
		t.Run(name, func(t *testing.T) {
			got, err := scm.RenderPR(cfg, "[kardinal] Promote web-v2 to prod", body)
			require.NoError(t, err)
			assert.Equal(t, "[kardinal] Promote web-v2 to prod", got.Title)
			assert.Equal(t, want, got.Body)
			assert.Empty(t, got.Labels)
			assert.Empty(t, got.Reviewers)
			assert.Empty(t, got.TeamReviewers)
			assert.Empty(t, got.Assignees)
		})
	}
}

// TestRenderPR_Templates covers each template field and the evidence
// functions a custom body keeps the default sections with.
//
// Covers SCM-PRCTL-TPL-01.
func TestRenderPR_Templates(t *testing.T) {
	body := prTemplateBody()
	defaultBody, err := scm.RenderPRBody(body)
	require.NoError(t, err)

	got, err := scm.RenderPR(&v1alpha1.PRConfig{
		TitleTemplate: "deploy {{ .Bundle.Version }}\nto {{ .Environment | upper }} ({{ .Bundle.CommitSHA | truncate 7 }})",
		BodyTemplate:  "Release {{ .Bundle.Name }} by @{{ .Bundle.Author }}\n\n{{ provenanceTable }}\n\n{{ gatesTable }}\n\n{{ upstreamTable }}",
		Labels:        []string{"env/{{ .Environment }}", "image/{{ (index .Bundle.Images 0).Tag }}", "kardinal", "  ", "env/prod"},
		Reviewers:     []string{"alice", "{{ .Bundle.Author }}"},
		TeamReviewers: []string{"platform"},
		Assignees:     []string{"{{ .Bundle.Author }}", "{{ if .IsRollback }}oncall{{ end }}"},
	}, "default", body)
	require.NoError(t, err)

	assert.Equal(t, "deploy 2.0.0 to PROD (abcdef0)", got.Title, "newlines in a title become spaces")
	assert.True(t, strings.HasPrefix(got.Body, "<!-- kardinal-promoter auto-generated PR -->\nRelease web-v2 by @octocat\n\n### Artifact Provenance\n"), got.Body)
	for _, section := range []string{"### Artifact Provenance", "### Policy Gate Compliance", "### Upstream Verification"} {
		i := strings.Index(defaultBody, section)
		require.GreaterOrEqual(t, i, 0)
		assert.Contains(t, got.Body, section)
	}
	assert.Contains(t, got.Body, `| soak | — | Pass | a \|\| b | 2026-03-04T05:06Z |`, "the gates table escapes cells as the default body does")
	assert.Contains(t, got.Body, "| uat | 2026-03-04T05:06Z | 30m |")
	assert.NotContains(t, got.Body, "Generated by", "only the sections the template asks for")

	assert.Equal(t, []string{"env/prod", "image/2.0.0", "kardinal"}, got.Labels, "one entry per line, blank lines and repeats dropped")
	assert.Equal(t, []string{"alice", "octocat"}, got.Reviewers)
	assert.Equal(t, []string{"platform"}, got.TeamReviewers)
	assert.Equal(t, []string{"octocat"}, got.Assignees, "a template that renders nothing adds nothing")
}

// TestRenderPR_EvidenceFunctions: evidence is the whole default body, and a
// rollback has its heading and notice.
//
// Covers SCM-PRCTL-TPL-01.
func TestRenderPR_EvidenceFunctions(t *testing.T) {
	body := prTemplateBody()
	defaultBody, err := scm.RenderPRBody(body)
	require.NoError(t, err)
	got, err := scm.RenderPR(&v1alpha1.PRConfig{BodyTemplate: "Hello\n{{ evidence }}"}, "t", body)
	require.NoError(t, err)
	assert.Equal(t, "<!-- kardinal-promoter auto-generated PR -->\nHello\n"+defaultBody, got.Body)

	got, err = scm.RenderPR(&v1alpha1.PRConfig{BodyTemplate: "{{ heading }}|{{ rollbackNotice }}|"}, "t", body)
	require.NoError(t, err)
	assert.Equal(t, "<!-- kardinal-promoter auto-generated PR -->\n## Promotion: web-v2 -> web/prod||", got.Body,
		"a promotion has no rollback notice")

	body.RollbackOf, body.RollbackFrom, body.RolledBackBy, body.RestoredVersion = "web-v1", "web-v2", "bob", "1.0.0"
	body.RollbackFromVersion = "2.0.0"
	got, err = scm.RenderPR(&v1alpha1.PRConfig{
		TitleTemplate: "{{ if .IsRollback }}revert {{ .Environment }} to {{ .Rollback.Restores }} ({{ .Rollback.Of }}, by {{ .Rollback.By }}){{ end }}",
		BodyTemplate:  "{{ rollbackNotice }}",
	}, "t", body)
	require.NoError(t, err)
	assert.Equal(t, "revert prod to 1.0.0 (web-v1, by bob)", got.Title)
	assert.Equal(t, "<!-- kardinal-promoter auto-generated PR -->\n"+
		"> **This is a rollback PR.** It restores the images of bundle web-v1 in environment prod.\n"+
		"> Rolling back FROM: web-v2 (2.0.0)\n> Rolling back TO: web-v1 (1.0.0)\n> Rolled back by: bob", got.Body)
}

// TestRenderPR_Errors: a template that does not parse or execute, an empty
// title, and labels the providers refuse are errors naming the field.
//
// Covers SCM-PRCTL-TPL-01.
func TestRenderPR_Errors(t *testing.T) {
	long := strings.Repeat("x", 51)
	tests := []struct {
		name string
		cfg  v1alpha1.PRConfig
		want string
	}{
		{"parse", v1alpha1.PRConfig{TitleTemplate: "{{ .Bundle.Name "}, "pr.titleTemplate:"},
		{"unknown field", v1alpha1.PRConfig{BodyTemplate: "{{ .Bundle.Nope }}"}, "pr.bodyTemplate:"},
		{"unknown function", v1alpha1.PRConfig{Labels: []string{"{{ nope }}"}}, "pr.labels[0]:"},
		{"empty title", v1alpha1.PRConfig{TitleTemplate: "{{ .Bundle.Author | trimPrefix \"octocat\" }}  "}, "pr.titleTemplate: rendered an empty title"},
		{"label too long", v1alpha1.PRConfig{Labels: []string{long}}, "longer than 50 characters"},
		{"label with comma", v1alpha1.PRConfig{Labels: []string{"a,b"}}, "has a comma"},
		{"reviewer error", v1alpha1.PRConfig{Reviewers: []string{"ok", "{{ .X }}"}}, "pr.reviewers[1]:"},
		{"team error", v1alpha1.PRConfig{TeamReviewers: []string{"{{ .X }}"}}, "pr.teamReviewers[0]:"},
		{"assignee error", v1alpha1.PRConfig{Assignees: []string{"{{ .X }}"}}, "pr.assignees[0]:"},
		{"too many entries", v1alpha1.PRConfig{Reviewers: manyReviewers(51)}, "renders 51 entries, more than 50"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := tt.cfg
			_, err := scm.RenderPR(&cfg, "t", prTemplateBody())
			require.Error(t, err)
			assert.Contains(t, err.Error(), tt.want)
		})
	}
}

// manyReviewers returns n distinct reviewer entries.
func manyReviewers(n int) []string {
	out := make([]string, n)
	for i := range out {
		out[i] = fmt.Sprintf("u%d", i)
	}
	return out
}

// TestPRTemplates_Sandbox: a pr template runs in the controller, so the
// constructs that grow a string without bound or spin are refused when the
// Pipeline is validated and when the step renders it: the 16-byte string
// doubled 24 times through variables (256 MiB), recursion through
// {{template}}, a range over a number, deep ranges, and a string builtin
// fed past its input limit.
//
// Covers SCM-PRCTL-TPL-01.
func TestPRTemplates_Sandbox(t *testing.T) {
	doubling := `{{$a := "xxxxxxxxxxxxxxxx"}}` + strings.Repeat(`{{$a = print $a $a}}`, 24) + `{{$a}}`
	tests := []struct {
		name string
		cfg  v1alpha1.PRConfig
		want string
	}{
		{"doubling body", v1alpha1.PRConfig{BodyTemplate: doubling}, "pr.bodyTemplate: variables are not allowed"},
		{"doubling title", v1alpha1.PRConfig{TitleTemplate: doubling}, "pr.titleTemplate: variables are not allowed"},
		{"doubling label", v1alpha1.PRConfig{Labels: []string{doubling}}, "pr.labels[0]: variables are not allowed"},
		{"doubling message", v1alpha1.PRConfig{Merge: &v1alpha1.PRMergeConfig{Auto: true, CommitMessageTemplate: doubling}},
			"pr.merge.commitMessageTemplate: variables are not allowed"},
		{"recursion", v1alpha1.PRConfig{BodyTemplate: `{{ define "r" }}{{ template "r" }}{{ end }}{{ template "r" }}`}, "pr.bodyTemplate: define and block are not allowed"},
		{"range over a number", v1alpha1.PRConfig{BodyTemplate: `{{ range 100000000 }}{{ end }}`}, "range is not allowed"},
		{"range over the images", v1alpha1.PRConfig{Labels: []string{`{{ range .Bundle.Images }}{{ .Tag }}{{ end }}`}}, "pr.labels[0]: range is not allowed"},
		{"printf", v1alpha1.PRConfig{TitleTemplate: `{{ printf "%999999999d" 1 }}`}, "printf is not available in this template"},
		{"printf argument indexes", v1alpha1.PRConfig{BodyTemplate: `{{ printf "%[1]s%[1]s%[1]s%[1]s" .Bundle.Name }}`}, "printf is not available in this template"},
		{"replace with an empty old", v1alpha1.PRConfig{TitleTemplate: `{{ replace "" "x" .Bundle.Name }}`}, "replace: the string to replace is empty"},
		{"output too long", v1alpha1.PRConfig{TitleTemplate: strings.Repeat("{{ evidence }}", 8)}, "pr.titleTemplate: template output is too large"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cfg := tt.cfg
			err := scm.ValidatePRConfig(&cfg)
			require.Error(t, err)
			assert.Contains(t, err.Error(), tt.want)
			_, err = scm.RenderPR(&cfg, "t", prTemplateBody())
			if cfg.Merge == nil {
				require.Error(t, err)
				assert.Contains(t, err.Error(), tt.want)
			}
		})
	}
}

// TestRenderPR_TitleIsBounded: a title is cut to 255 characters.
func TestRenderPR_TitleIsBounded(t *testing.T) {
	got, err := scm.RenderPR(&v1alpha1.PRConfig{TitleTemplate: strings.Repeat("é", 300)}, "t", prTemplateBody())
	require.NoError(t, err)
	assert.Equal(t, 255, len([]rune(got.Title)))
}

// TestRenderPR_NoProvenance: a Bundle without provenance renders its fields
// as empty strings, not a nil pointer error.
func TestRenderPR_NoProvenance(t *testing.T) {
	body := prTemplateBody()
	body.Bundle.Provenance = nil
	got, err := scm.RenderPR(&v1alpha1.PRConfig{
		TitleTemplate: "by {{ .Bundle.Author | default \"ci\" }}",
		Assignees:     []string{"{{ .Bundle.Author }}"},
	}, "t", body)
	require.NoError(t, err)
	assert.Equal(t, "by ci", got.Title)
	assert.Empty(t, got.Assignees)
}

// TestRenderMergeOptions: the method defaults to merge; the first line of the
// message is the commit title and the rest the body; the PR is in the data.
func TestRenderMergeOptions(t *testing.T) {
	body := prTemplateBody()
	pr := scm.PRTemplatePR{Number: 42, URL: "https://scm/pr/42", Title: "deploy 2.0.0"}

	opts, err := scm.RenderMergeOptions(&v1alpha1.PRMergeConfig{Auto: true}, body, pr)
	require.NoError(t, err)
	assert.Equal(t, scm.MergeOptions{Method: "merge"}, opts)

	opts, err = scm.RenderMergeOptions(&v1alpha1.PRMergeConfig{Auto: true, Method: "squash",
		CommitMessageTemplate: "\n{{ .PR.Title }} (#{{ .PR.Number }})\n\nBundle {{ .Bundle.Name }}\n{{ .PR.URL }}\n"}, body, pr)
	require.NoError(t, err)
	assert.Equal(t, scm.MergeOptions{Method: "squash", CommitTitle: "deploy 2.0.0 (#42)",
		CommitBody: "Bundle web-v2\nhttps://scm/pr/42"}, opts)

	_, err = scm.RenderMergeOptions(&v1alpha1.PRMergeConfig{Auto: true, CommitMessageTemplate: "{{ if false }}x{{ end }}"}, body, pr)
	assert.ErrorContains(t, err, "rendered an empty message")
	_, err = scm.RenderMergeOptions(&v1alpha1.PRMergeConfig{Auto: true, CommitMessageTemplate: "{{ .PR.Nope }}"}, body, pr)
	assert.ErrorContains(t, err, "pr.merge.commitMessageTemplate:")
}

// TestValidatePipelinePR: the Pipeline reconciler and kardinal validate
// render every template with sample data for a promotion and a rollback, so
// a template that only fails for one of them is caught before a Bundle.
//
// Covers SCM-PRCTL-TPL-01.
func TestValidatePipelinePR(t *testing.T) {
	pipeline := func(pr *v1alpha1.PRConfig) *v1alpha1.Pipeline {
		return &v1alpha1.Pipeline{Spec: v1alpha1.PipelineSpec{Environments: []v1alpha1.EnvironmentSpec{
			{Name: "test"}, {Name: "prod", Approval: "pr-review", PR: pr},
		}}}
	}
	tests := []struct {
		name string
		pr   *v1alpha1.PRConfig
		want string
	}{
		{name: "no pr config"},
		{name: "valid", pr: &v1alpha1.PRConfig{TitleTemplate: "{{ .Bundle.Version }}", Labels: []string{"x"},
			Merge: &v1alpha1.PRMergeConfig{Auto: true, CommitMessageTemplate: "{{ .PR.Title }}"}}},
		{name: "parse error", pr: &v1alpha1.PRConfig{BodyTemplate: "{{ if }}"}, want: `environment "prod": pr.bodyTemplate:`},
		{name: "rollback only", pr: &v1alpha1.PRConfig{TitleTemplate: `{{ if .IsRollback }}{{ .Rollback.Nope }}{{ else }}ok{{ end }}`},
			want: `environment "prod": pr.titleTemplate:`},
		{name: "empty for a promotion", pr: &v1alpha1.PRConfig{TitleTemplate: `{{ if .IsRollback }}r{{ end }}`},
			want: "rendered an empty title"},
		{name: "merge message", pr: &v1alpha1.PRConfig{Merge: &v1alpha1.PRMergeConfig{Auto: true, CommitMessageTemplate: "{{ .Nope }}"}},
			want: "pr.merge.commitMessageTemplate:"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := scm.ValidatePipelinePR(pipeline(tt.pr))
			if tt.want == "" {
				assert.NoError(t, err)
				return
			}
			require.Error(t, err)
			assert.Contains(t, err.Error(), tt.want)
		})
	}
}

// TestCheckPRSupport: every control a provider lacks fails the check with
// the field and the provider, and the merge method must be one the provider
// takes.
func TestCheckPRSupport(t *testing.T) {
	providers := map[string]scm.SCMProvider{}
	for _, kind := range []string{"github", "gitlab", "forgejo", "bitbucket", "azuredevops"} {
		p, err := scm.NewProvider(kind, "t", "", "")
		require.NoError(t, err)
		providers[kind] = p
	}
	dc, err := scm.NewProvider("bitbucket-datacenter", "t", "https://git.example.com", "")
	require.NoError(t, err)
	providers["bitbucket-datacenter"] = dc
	dyn, err := scm.NewDynamicProvider("gitlab", "t", "", "")
	require.NoError(t, err)
	providers["dynamic gitlab"] = dyn

	auto := func(method, msg string) *v1alpha1.PRConfig {
		return &v1alpha1.PRConfig{Merge: &v1alpha1.PRMergeConfig{Auto: true, Method: method, CommitMessageTemplate: msg}}
	}
	type check struct {
		provider string
		cfg      *v1alpha1.PRConfig
		want     string // "" = supported
	}
	checks := []check{
		{"github", &v1alpha1.PRConfig{Labels: []string{"a"}, Reviewers: []string{"a"}, TeamReviewers: []string{"t"}, Assignees: []string{"a"}}, ""},
		{"github", auto("rebase", "m"), ""},
		{"gitlab", &v1alpha1.PRConfig{Labels: []string{"a"}, Reviewers: []string{"a"}, Assignees: []string{"a"}}, ""},
		{"gitlab", &v1alpha1.PRConfig{TeamReviewers: []string{"t"}}, "pr.teamReviewers is not supported by the gitlab SCM provider"},
		{"gitlab", auto("squash", "m"), ""},
		{"gitlab", auto("rebase", ""), "pr.merge.method rebase is not supported by the gitlab SCM provider"},
		{"dynamic gitlab", auto("rebase", ""), "pr.merge.method rebase is not supported by the gitlab SCM provider"},
		{"forgejo", &v1alpha1.PRConfig{Labels: []string{"a"}, Reviewers: []string{"a"}, TeamReviewers: []string{"t"}, Assignees: []string{"a"}}, ""},
		{"forgejo", auto("", "m"), ""},
		{"bitbucket", &v1alpha1.PRConfig{Reviewers: []string{"{uuid}"}}, ""},
		{"bitbucket", &v1alpha1.PRConfig{Labels: []string{"a"}}, "pr.labels is not supported by the bitbucket SCM provider"},
		{"bitbucket", &v1alpha1.PRConfig{Assignees: []string{"a"}}, "pr.assignees is not supported"},
		{"bitbucket", &v1alpha1.PRConfig{TeamReviewers: []string{"a"}}, "pr.teamReviewers is not supported"},
		{"bitbucket", auto("", ""), "pr.merge.auto is not supported by the bitbucket SCM provider"},
		{"bitbucket", &v1alpha1.PRConfig{Merge: &v1alpha1.PRMergeConfig{}}, ""},
		{"azuredevops", &v1alpha1.PRConfig{Labels: []string{"a"}, Reviewers: []string{"id"}, TeamReviewers: []string{"id"}}, ""},
		{"azuredevops", &v1alpha1.PRConfig{Assignees: []string{"a"}}, "pr.assignees is not supported by the azuredevops SCM provider"},
		{"azuredevops", auto("rebase", "m"), ""},
		{"bitbucket-datacenter", &v1alpha1.PRConfig{Reviewers: []string{"alice"}}, ""},
		{"bitbucket-datacenter", auto("squash", "m"), ""},
		{"bitbucket-datacenter", &v1alpha1.PRConfig{Labels: []string{"a"}}, "pr.labels is not supported by the bitbucket-datacenter SCM provider"},
		{"bitbucket-datacenter", &v1alpha1.PRConfig{TeamReviewers: []string{"t"}}, "pr.teamReviewers is not supported"},
		{"bitbucket-datacenter", &v1alpha1.PRConfig{Assignees: []string{"a"}}, "pr.assignees is not supported by the bitbucket-datacenter SCM provider"},
	}
	for _, c := range checks {
		err := scm.CheckPRSupport(c.cfg, scm.SupportOf(providers[c.provider]))
		if c.want == "" {
			assert.NoError(t, err, "%s %+v", c.provider, c.cfg)
			continue
		}
		if assert.Error(t, err, "%s %+v", c.provider, c.cfg) {
			assert.Contains(t, err.Error(), c.want)
			assert.Contains(t, err.Error(), "docs/scm-providers.md#pr-controls")
		}
	}
	assert.NoError(t, scm.CheckPRSupport(nil, scm.PRSupport{}))
}

// TestPRTemplateData_Bounded: the template data keeps at most 20 images
// and 1024 characters per value, and a list template refuses a value with a
// line break, which would otherwise split into several entries (an author
// "alice\nbob" would assign two users).
//
// Covers SCM-PRCTL-TPL-01.
func TestPRTemplateData_Bounded(t *testing.T) {
	body := prTemplateBody()
	for i := 0; i < 30; i++ {
		body.Bundle.Images = append(body.Bundle.Images, v1alpha1.ImageRef{Repository: fmt.Sprintf("r/i%d", i), Tag: "1"})
	}
	body.Bundle.Provenance.Author = strings.Repeat("a", 2000)
	d := scm.NewPRTemplateData(body)
	assert.Len(t, d.Bundle.Images, 20)
	assert.Equal(t, 1024, len(d.Bundle.Author))

	body = prTemplateBody()
	body.Bundle.Provenance.Author = "alice\nbob"
	_, err := scm.RenderPR(&v1alpha1.PRConfig{Assignees: []string{"{{ .Bundle.Author }}"}}, "t", body)
	assert.ErrorContains(t, err, "pr.assignees: .Bundle.Author has a line break")
	got, err := scm.RenderPR(&v1alpha1.PRConfig{TitleTemplate: "by {{ .Bundle.Author }}"}, "t", body)
	require.NoError(t, err, "a title is one line anyway")
	assert.Equal(t, "by alice bob", got.Title)
}

// TestNewPRTemplateData_Bounded: every string of the template data, the
// image fields included, is cut to 1024 characters and the images to 20, so
// what a template reads is bounded whatever the Bundle holds; imageList
// lists them one per line; a line break in any string refuses a list.
//
// Covers SCM-PRCTL-TPL-01.
func TestNewPRTemplateData_Bounded(t *testing.T) {
	long := strings.Repeat("x", 5000)
	body := prTemplateBody()
	body.PipelineName, body.Environment, body.BundleName = long, long, long
	body.Bundle.Images = nil
	for i := 0; i < 30; i++ {
		body.Bundle.Images = append(body.Bundle.Images, v1alpha1.ImageRef{Repository: long, Tag: long, Digest: long})
	}
	d := scm.NewPRTemplateData(body)
	require.Len(t, d.Bundle.Images, 20)
	for _, s := range []string{d.Pipeline, d.Environment, d.Bundle.Name, d.Bundle.Version,
		d.Bundle.Images[0].Repository, d.Bundle.Images[0].Tag, d.Bundle.Images[19].Digest} {
		assert.LessOrEqual(t, len([]rune(s)), 1024)
	}

	body = prTemplateBody()
	body.Bundle.Images = []v1alpha1.ImageRef{{Repository: "ghcr.io/a/web", Tag: "2.0.0"}, {Repository: "ghcr.io/a/api", Tag: "1.1", Digest: "sha256:ab"}}
	got, err := scm.RenderPR(&v1alpha1.PRConfig{BodyTemplate: "{{ imageList }}"}, "t", body)
	require.NoError(t, err)
	assert.Equal(t, "<!-- kardinal-promoter auto-generated PR -->\nghcr.io/a/web:2.0.0\nghcr.io/a/api:1.1@sha256:ab", got.Body)

	body.Bundle.Images[1].Tag = "1.1\nevil"
	_, err = scm.RenderPR(&v1alpha1.PRConfig{Labels: []string{"x"}}, "t", body)
	require.Error(t, err)
	assert.Contains(t, err.Error(), "has a line break")
	body = prTemplateBody()
	body.BundleName = "web\nv2"
	_, err = scm.RenderPR(&v1alpha1.PRConfig{Reviewers: []string{"x"}}, "t", body)
	require.Error(t, err)
	assert.Contains(t, err.Error(), ".Bundle.Name has a line break")
}

// TestRenderPR_PrintTheDataIsRefused (#1474 review): {{print . . ...}} with
// 8000 dots passes the whole data struct to print 8000 times. It is refused
// before anything formats it, fast and without a large allocation.
//
// Covers SCM-PRCTL-TPL-01.
func TestRenderPR_PrintTheDataIsRefused(t *testing.T) {
	text := "{{ print" + strings.Repeat(" .", 8000) + " }}"
	var before, after runtime.MemStats
	runtime.GC()
	runtime.ReadMemStats(&before)
	start := time.Now()
	_, err := scm.RenderPR(&v1alpha1.PRConfig{BodyTemplate: text}, "t", prTemplateBody())
	elapsed := time.Since(start)
	runtime.ReadMemStats(&after)
	require.Error(t, err)
	assert.Contains(t, err.Error(), "print: takes strings, numbers and bools only")
	assert.Less(t, after.TotalAlloc-before.TotalAlloc, uint64(64<<20), "no formatting of the data")
	assert.Less(t, elapsed, 2*time.Second)
}

// TestRenderPR_EvidenceRenderedOnce: the template functions are built once
// per RenderPR and the evidence sections render on first use, so 80 small
// templates over a Bundle of 100 images (the CRD maximum) do not render the
// default body 80 times.
//
// Covers SCM-PRCTL-TPL-01.
func TestRenderPR_EvidenceRenderedOnce(t *testing.T) {
	body := prTemplateBody()
	body.Bundle.Images = nil
	for i := 0; i < 100; i++ {
		body.Bundle.Images = append(body.Bundle.Images, v1alpha1.ImageRef{Repository: fmt.Sprintf("ghcr.io/acme/svc-%03d", i), Tag: "1.0.0"})
	}
	cfg := &v1alpha1.PRConfig{BodyTemplate: "{{ evidence }}{{ provenanceTable }}"}
	for i := 0; i < 80; i++ {
		// 80 templates, 40 of them rendering one entry each, under the
		// list cap of 50.
		cfg.Labels = append(cfg.Labels, fmt.Sprintf("{{ if provenanceTable }}l%d{{ end }}", i%40))
	}
	var before, after runtime.MemStats
	runtime.GC()
	runtime.ReadMemStats(&before)
	start := time.Now()
	_, err := scm.RenderPR(cfg, "t", body)
	elapsed := time.Since(start)
	runtime.ReadMemStats(&after)
	require.NoError(t, err)
	assert.Less(t, after.TotalAlloc-before.TotalAlloc, uint64(64<<20))
	assert.Less(t, elapsed, 2*time.Second)
}
