// Copyright 2026 The kardinal-promoter Authors.
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package scm

import (
	"bytes"
	"fmt"
	"text/template"
	"time"

	v1alpha1 "github.com/kardinal-promoter/kardinal-promoter/api/v1alpha1"
)

// PRBody holds the data used to render the PR body template.
type PRBody struct {
	// Pipeline is the Pipeline CRD spec.
	Pipeline v1alpha1.PipelineSpec

	// PipelineName is the pipeline resource name.
	PipelineName string

	// Environment is the target environment name.
	Environment string

	// Bundle holds the Bundle being promoted.
	Bundle v1alpha1.BundleSpec

	// BundleName is the Bundle resource name.
	BundleName string

	// GateResults holds PolicyGate evaluation results for this environment.
	GateResults []v1alpha1.GateResult

	// UpstreamEnvironments holds verification evidence for upstream environments.
	UpstreamEnvironments []v1alpha1.EnvironmentStatus
}

// elapsedSince returns a human-readable elapsed time string since t.
func elapsedSince(t time.Time) string {
	d := time.Since(t)
	if d < 0 {
		d = -d
	}
	minutes := int(d.Minutes())
	if minutes < 60 {
		return fmt.Sprintf("%dm", minutes)
	}
	hours := int(d.Hours())
	if hours < 24 {
		return fmt.Sprintf("%dh%dm", hours, minutes%60)
	}
	return fmt.Sprintf("%dd", int(d.Hours()/24))
}

var prBodyTemplate = template.Must(template.New("pr-body").Funcs(template.FuncMap{
	"elapsed": elapsedSince,
}).Parse(`
<!-- kardinal-promoter auto-generated PR -->
## Promotion: {{.BundleName}} → {{.PipelineName}}/{{.Environment}}

### Artifact Provenance

| Image | Tag | Digest | CI Run | Commit SHA | Author |
|---|---|---|---|---|---|
{{- range .Bundle.Images}}
| {{.Repository}} | {{if .Tag}}{{.Tag}}{{else}}—{{end}} | {{if .Digest}}{{.Digest}}{{else}}—{{end}} | {{if $.Bundle.Provenance}}[CI run]({{$.Bundle.Provenance.CIRunURL}}){{else}}—{{end}} | {{if $.Bundle.Provenance}}{{$.Bundle.Provenance.CommitSHA}}{{else}}—{{end}} | {{if $.Bundle.Provenance}}{{$.Bundle.Provenance.Author}}{{else}}—{{end}} |
{{- else}}
| — | — | — | — | — | — |
{{- end}}

### Policy Gate Compliance

| Gate | Namespace | Result | Reason | Last Evaluated |
|---|---|---|---|---|
{{- range .GateResults}}
| {{.GateName}} | {{if .GateNamespace}}{{.GateNamespace}}{{else}}—{{end}} | {{.Result}} | {{.Reason}} | {{.EvaluatedAt.UTC.Format "2006-01-02T15:04Z"}} |
{{- else}}
| _(none)_ | — | — | — | — |
{{- end}}

### Upstream Verification

| Environment | Health Checked At | Elapsed |
|---|---|---|
{{- range .UpstreamEnvironments}}
| {{.Name}} | {{if .HealthCheckedAt}}{{.HealthCheckedAt.UTC.Format "2006-01-02T15:04Z"}}{{else}}—{{end}} | {{if .HealthCheckedAt}}{{elapsed .HealthCheckedAt.Time}}{{else}}—{{end}} |
{{- else}}
| _(none)_ | — | — |
{{- end}}

---
*Generated by [kardinal-promoter](https://github.com/pnz1990/kardinal-promoter)*
`))

// RenderPRBody renders the PR body template with the given data.
func RenderPRBody(data PRBody) (string, error) {
	var buf bytes.Buffer
	if err := prBodyTemplate.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("render PR body: %w", err)
	}
	return buf.String(), nil
}
