apiVersion: kardinal.io/v1alpha1
kind: Pipeline
metadata:
  name: kardinal-test-app-flux
  namespace: default
spec:
  git:
    url: https://github.com/pnz1990/kardinal-demo
    branch: main
    layout: directory
    provider: github
    secretRef:
      name: github-token
  environments:
    - name: test
      path: environments/test
      update:
        strategy: kustomize
      approval: auto
      health:
        type: flux
        flux:
          name: kardinal-test-app-flux-test
          namespace: flux-system
    - name: uat
      path: environments/uat
      update:
        strategy: kustomize
      approval: auto
      health:
        type: flux
        flux:
          name: kardinal-test-app-flux-uat
          namespace: flux-system
  historyLimit: 5
