// Copyright 2026 The kardinal-promoter Authors.
// Licensed under the Apache License, Version 2.0

// hack/gen-cli-docs/main.go generates one Markdown page per kardinal CLI
// subcommand using Cobra's built-in doc generator. Output is placed in
// docs/reference/cli/ and is consumed by mkdocs during the docs build.
//
// Run:
//
//	go run ./hack/gen-cli-docs/main.go
//	go run ./hack/gen-cli-docs/main.go --output docs/reference/cli/
package main

import (
	"flag"
	"log"
	"os"
	"path/filepath"
	"strings"

	kardinalcmd "github.com/kardinal-promoter/kardinal-promoter/cmd/kardinal/cmd"
	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
)

func main() {
	outDir := flag.String("output", "docs/reference/cli/", "output directory for generated CLI docs")
	flag.Parse()

	if err := os.MkdirAll(*outDir, 0o755); err != nil {
		log.Fatalf("create output dir: %v", err)
	}

	root := kardinalcmd.NewRootCmd()

	// DisableAutoGenTag removes the "Auto generated by spf13/cobra" footer
	// so the pages don't contain a timestamp that changes every build.
	setDisableAutoGenTag(root)

	// Generate one .md file per command and subcommand.
	// cobra/doc names them like: kardinal.md, kardinal_get.md, kardinal_get_pipelines.md
	if err := doc.GenMarkdownTree(root, *outDir); err != nil {
		log.Fatalf("generate docs: %v", err)
	}

	// Rename underscores to hyphens for cleaner URLs (kardinal_get → kardinal-get)
	entries, err := os.ReadDir(*outDir)
	if err != nil {
		log.Fatalf("read output dir: %v", err)
	}
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".md") {
			continue
		}
		newName := strings.ReplaceAll(e.Name(), "_", "-")
		if newName != e.Name() {
			old := filepath.Join(*outDir, e.Name())
			new := filepath.Join(*outDir, newName)
			if err := os.Rename(old, new); err != nil {
				log.Printf("rename %s: %v", e.Name(), err)
			}
		}
	}

	log.Printf("CLI docs generated in %s", *outDir)
}

// setDisableAutoGenTag recursively sets DisableAutoGenTag on every command.
func setDisableAutoGenTag(cmd *cobra.Command) {
	cmd.DisableAutoGenTag = true
	for _, sub := range cmd.Commands() {
		setDisableAutoGenTag(sub)
	}
}
