// Copyright 2026 The kardinal-promoter Authors.
// Licensed under the Apache License, Version 2.0

// hack/gen-cli-docs/main.go generates CLI reference documentation from the
// kardinal Cobra command tree. It produces:
//
//   - docs/reference/cli/kardinal-*.md  — one page per command (detail)
//   - docs/cli-reference.md             — consolidated quick-reference table
//
// The consolidated page replaces the hand-authored docs/cli-reference.md.
// Both outputs are consumed by mkdocs during the docs build.
//
// Run:
//
//	go run ./hack/gen-cli-docs/main.go
//	go run ./hack/gen-cli-docs/main.go --output /tmp/cli/ --quickref /tmp/cli-reference.md
//
// Design ref: docs/design/41-published-docs-freshness.md §41.1
package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"

	kardinalcmd "github.com/kardinal-promoter/kardinal-promoter/cmd/kardinal/cmd"
)

func main() {
	outDir := flag.String("output", "docs/reference/cli/", "output directory for generated CLI docs")
	quickRefPath := flag.String("quickref", "docs/cli-reference.md", "output file for the consolidated quick-reference page")
	flag.Parse()

	if err := os.MkdirAll(*outDir, 0o755); err != nil {
		log.Fatalf("create output dir: %v", err)
	}

	root := kardinalcmd.NewRootCmd()

	// DisableAutoGenTag removes the "Auto generated by spf13/cobra" footer
	// so the pages don't contain a timestamp that changes every build.
	setDisableAutoGenTag(root)

	// Generate one .md file per command and subcommand. Files are renamed to
	// hyphens below, so SEE ALSO links use hyphens too.
	noPrepend := func(string) string { return "" }
	hyphenLink := func(name string) string { return strings.ReplaceAll(name, "_", "-") }
	if err := doc.GenMarkdownTreeCustom(root, *outDir, noPrepend, hyphenLink); err != nil {
		log.Fatalf("generate docs: %v", err)
	}

	// Rename underscores to hyphens for cleaner URLs (kardinal_get -> kardinal-get)
	entries, err := os.ReadDir(*outDir)
	if err != nil {
		log.Fatalf("read output dir: %v", err)
	}
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".md") {
			continue
		}
		newName := strings.ReplaceAll(e.Name(), "_", "-")
		if newName != e.Name() {
			old := filepath.Join(*outDir, e.Name())
			newPath := filepath.Join(*outDir, newName)
			if err := os.Rename(old, newPath); err != nil {
				log.Fatalf("rename %s: %v", e.Name(), err)
			}
		}
	}

	// Generate the consolidated quick-reference page (docs/cli-reference.md).
	// This replaces the hand-authored version that was drifting out of sync.
	if err := genQuickReference(root, *quickRefPath); err != nil {
		log.Fatalf("generate %s: %v", *quickRefPath, err)
	}
	log.Printf("CLI quick-reference generated: %s", *quickRefPath)

	log.Printf("CLI docs generated in %s", *outDir)
}

// genQuickReference writes docs/cli-reference.md as an auto-generated command table.
// Each row links to the per-command detail page in docs/reference/cli/.
func genQuickReference(root *cobra.Command, outPath string) error {
	type cmdEntry struct {
		name string
		desc string
		link string
	}

	var cmdEntries []cmdEntry
	var walk func(cmd *cobra.Command, prefix string)
	walk = func(cmd *cobra.Command, prefix string) {
		// Deprecated commands are skipped, as doc.GenMarkdownTree skips them,
		// so every row links to a generated page.
		if cmd.Hidden || cmd.Deprecated != "" || cmd.Name() == "help" {
			return
		}
		fullName := strings.TrimSpace(prefix + " " + cmd.Name())
		if fullName != "kardinal" && cmd.Short != "" {
			linkName := strings.ReplaceAll(fullName, " ", "-") + ".md"
			cmdEntries = append(cmdEntries, cmdEntry{
				name: fullName,
				desc: cmd.Short,
				link: "reference/cli/" + linkName,
			})
		}
		for _, sub := range cmd.Commands() {
			walk(sub, fullName)
		}
	}
	walk(root, "")

	sort.Slice(cmdEntries, func(i, j int) bool {
		return cmdEntries[i].name < cmdEntries[j].name
	})

	var b strings.Builder
	b.WriteString("# CLI Reference\n\n")
	b.WriteString("<!-- AUTO-GENERATED — do not edit by hand.\n")
	b.WriteString("     Run: go run ./hack/gen-cli-docs/main.go to regenerate.\n")
	b.WriteString("     Design ref: docs/design/41-published-docs-freshness.md -->\n\n")
	b.WriteString("!!! note \"Auto-generated\"\n")
	b.WriteString("    Generated from the kardinal CLI source. Every command is documented.\n")
	b.WriteString("    See [detailed reference pages](reference/cli/kardinal.md) for flags and examples.\n\n")
	b.WriteString("| Command | Description |\n")
	b.WriteString("|---|---|\n")

	for _, e := range cmdEntries {
		fmt.Fprintf(&b, "| [`%s`](%s) | %s |\n", e.name, e.link, e.desc)
	}

	b.WriteString("\nFor full flag documentation, examples, and output formats, see the\n")
	b.WriteString("[individual command pages](reference/cli/kardinal.md).\n")
	if err := os.WriteFile(outPath, []byte(b.String()), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", outPath, err)
	}
	return nil
}

// setDisableAutoGenTag recursively sets DisableAutoGenTag on every command.
func setDisableAutoGenTag(cmd *cobra.Command) {
	cmd.DisableAutoGenTag = true
	for _, sub := range cmd.Commands() {
		setDisableAutoGenTag(sub)
	}
}
