apiVersion: kardinal.io/v1alpha1
kind: Pipeline
metadata:
  name: kardinal-test-app
  namespace: default
spec:
  environments:
  - approval: auto
    health:
      resource:
        condition: Available
        name: kardinal-test-app
        namespace: kardinal-test-app-test
      type: resource
    name: test
    path: environments/test
    update:
      strategy: kustomize
  - approval: auto
    bake:
      minutes: 5
    health:
      resource:
        name: kardinal-test-app
        namespace: kardinal-test-app-uat
      type: resource
    name: uat
    path: environments/uat
    update:
      strategy: kustomize
  - approval: pr-review
    health:
      timeout: 30m
      type: flagger
    name: prod
    path: environments/prod
    update:
      strategy: kustomize
  git:
    branch: main
    layout: directory
    provider: github
    secretRef:
      name: github-token
    url: https://github.com/pnz1990/kardinal-demo
  historyLimit: 20
