// Copyright 2026 The kardinal-promoter Authors.
// Licensed under the Apache License, Version 2.0

// hack/gen-api-docs/main.go writes docs/reference/api.md from the CRDs in
// config/crd/bases, which controller-gen generates from api/v1alpha1. Every
// field of every kind is listed with its type, whether it is required, and its
// description, enum and default from the schema.
//
// Run it through `make api-docs` (`make manifests` runs it too).
// TestAPIReferenceIsUpToDate fails when the committed page is stale.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"

	apiextv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	sigyaml "sigs.k8s.io/yaml"
)

func main() {
	crdDir := flag.String("crds", "config/crd/bases", "directory holding the generated CRD YAML files")
	out := flag.String("output", "docs/reference/api.md", "file to write")
	flag.Parse()

	page, err := render(*crdDir)
	if err != nil {
		log.Fatalf("render API reference: %v", err)
	}
	if err := os.WriteFile(*out, page, 0o644); err != nil {
		log.Fatalf("write %s: %v", *out, err)
	}
}

const header = `# API Reference

<!-- Generated by hack/gen-api-docs from config/crd/bases. Do not edit; run "make api-docs". -->

This page is generated from the CRD schemas in ` + "`config/crd/bases/`" + `, which
controller-gen builds from the Go types in ` + "`api/v1alpha1/`" + `. Run ` + "`make api-docs`" + `
(or ` + "`make manifests`" + `) after changing the types; CI fails when this page is stale.

` + "`kubectl explain <kind>.spec`" + ` shows the same descriptions on a cluster. Gate labels such as
` + "`kardinal.io/scope`" + ` are covered in [Policy Gates](../policy-gates.md), and the variables a
PolicyGate expression can use in [CEL Context](cel-context.md).
`

// render returns the API reference page for the CRDs in dir.
func render(dir string) ([]byte, error) {
	files, err := filepath.Glob(filepath.Join(dir, "*.yaml"))
	if err != nil {
		return nil, fmt.Errorf("list %s: %w", dir, err)
	}
	if len(files) == 0 {
		return nil, fmt.Errorf("no CRD files in %s", dir)
	}
	var crds []apiextv1.CustomResourceDefinition
	for _, f := range files {
		raw, err := os.ReadFile(f)
		if err != nil {
			return nil, fmt.Errorf("read %s: %w", f, err)
		}
		var crd apiextv1.CustomResourceDefinition
		if err := sigyaml.Unmarshal(raw, &crd); err != nil {
			return nil, fmt.Errorf("parse %s: %w", f, err)
		}
		crds = append(crds, crd)
	}
	sort.Slice(crds, func(i, j int) bool { return crds[i].Spec.Names.Kind < crds[j].Spec.Names.Kind })

	var b bytes.Buffer
	b.WriteString(header)
	b.WriteString("\n| Kind | Resource | Scope | Short names |\n|---|---|---|---|\n")
	for _, crd := range crds {
		n := crd.Spec.Names
		fmt.Fprintf(&b, "| [%s](#%s) | `%s` | %s | %s |\n", n.Kind, strings.ToLower(n.Kind), crd.Name, crd.Spec.Scope, code(n.ShortNames))
	}
	for _, crd := range crds {
		for _, v := range crd.Spec.Versions {
			if v.Schema == nil || v.Schema.OpenAPIV3Schema == nil {
				continue
			}
			s := v.Schema.OpenAPIV3Schema
			fmt.Fprintf(&b, "\n## %s\n\n`%s/%s`\n\n%s\n", crd.Spec.Names.Kind, crd.Spec.Group, v.Name, oneLine(s.Description))
			b.WriteString("\n| Field | Type | Required | Description |\n|---|---|---|---|\n")
			for _, top := range []string{"spec", "status"} {
				if p, ok := s.Properties[top]; ok {
					writeFields(&b, top, p, contains(s.Required, top))
				}
			}
		}
	}
	return b.Bytes(), nil
}

// writeFields writes the row for path and then the rows of its sub-fields.
func writeFields(b *bytes.Buffer, path string, s apiextv1.JSONSchemaProps, required bool) {
	req := ""
	if required {
		req = "yes"
	}
	fmt.Fprintf(b, "| `%s` | %s | %s | %s |\n", path, typeName(s), req, cell(s))
	if s.Type == "array" && s.Items != nil && s.Items.Schema != nil {
		path += "[]"
		s = *s.Items.Schema
	}
	names := make([]string, 0, len(s.Properties))
	for name := range s.Properties {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		writeFields(b, path+"."+name, s.Properties[name], contains(s.Required, name))
	}
}

func typeName(s apiextv1.JSONSchemaProps) string {
	switch {
	case s.XIntOrString:
		return "int or string"
	case s.Type == "array" && s.Items != nil && s.Items.Schema != nil:
		return "[]" + typeName(*s.Items.Schema)
	case s.Type == "object" && s.AdditionalProperties != nil && s.AdditionalProperties.Schema != nil:
		return "map[string]" + typeName(*s.AdditionalProperties.Schema)
	case s.Type == "":
		return "any"
	case s.Format != "":
		return s.Type + " (" + s.Format + ")"
	}
	return s.Type
}

// cell is the description column: the description, then the enum and default.
func cell(s apiextv1.JSONSchemaProps) string {
	parts := []string{oneLine(s.Description)}
	if len(s.Enum) > 0 {
		vals := make([]string, 0, len(s.Enum))
		for _, e := range s.Enum {
			vals = append(vals, strings.Trim(string(e.Raw), `"`))
		}
		parts = append(parts, "One of: "+code(vals)+".")
	}
	if s.Default != nil {
		parts = append(parts, "Default: `"+strings.Trim(string(s.Default.Raw), `"`)+"`.")
	}
	return strings.TrimSpace(strings.Join(parts, " "))
}

// oneLine makes a description safe for a Markdown table cell.
func oneLine(s string) string {
	s = strings.Join(strings.Fields(s), " ")
	return strings.NewReplacer("|", `\|`, "<", "&lt;", ">", "&gt;").Replace(s)
}

func code(vals []string) string {
	out := make([]string, 0, len(vals))
	for _, v := range vals {
		out = append(out, "`"+v+"`")
	}
	return strings.Join(out, ", ")
}

func contains(list []string, s string) bool {
	for _, v := range list {
		if v == s {
			return true
		}
	}
	return false
}
