apiVersion: kardinal.io/v1alpha1
kind: Pipeline
metadata:
  name: kardinal-test-app-flagger
  namespace: default
spec:
  git:
    url: https://github.com/pnz1990/kardinal-demo
    branch: main
    layout: directory
    provider: github
    secretRef:
      name: github-token
  environments:
    - name: test
      path: environments/test
      update:
        strategy: kustomize
      approval: auto
      health:
        type: flagger
        # Canary name is derived: <pipeline> = kardinal-test-app-flagger, namespace = <env>
        # = kardinal-test-app-test
        timeout: 5m
  historyLimit: 5
