apiVersion: kardinal.io/v1alpha1
kind: Pipeline
metadata:
  name: nginx-demo
  namespace: default
  labels:
    app: nginx-demo
spec:
  environments:
    - name: test
      gitRepo: https://github.com/myorg/gitops.git
      branch: main
      path: apps/nginx/overlays/test
      approvalMode: auto
      updateStrategy: kustomize
      healthAdapter: deployment
      healthTimeout: 30m
      gitCredentials:
        secretName: gitops-creds
        secretNamespace: default
    - name: uat
      gitRepo: https://github.com/myorg/gitops.git
      branch: main
      path: apps/nginx/overlays/uat
      approvalMode: auto
      updateStrategy: kustomize
      healthAdapter: deployment
      healthTimeout: 30m
      dependsOn:
        - test
    - name: prod
      gitRepo: https://github.com/myorg/gitops.git
      branch: main
      path: apps/nginx/overlays/prod
      approvalMode: pr-review
      updateStrategy: kustomize
      healthAdapter: argocd
      healthTimeout: 60m
      deliveryDelegate: argoRollouts
      dependsOn:
        - uat
  policyGates:
    - name: no-weekend-deploys
      namespace: platform-policies
  paused: false
