// Copyright 2026 The kardinal-promoter Authors.
// Licensed under the Apache License, Version 2.0

package v1alpha1_test

import (
	"encoding/json"
	"testing"

	"github.com/kardinal-promoter/kardinal-promoter/api/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// TestPipelineRoundtrip verifies that Pipeline serializes and deserializes
// correctly via JSON (the format used by the Kubernetes API server).
func TestPipelineRoundtrip(t *testing.T) {
	original := &v1alpha1.Pipeline{
		TypeMeta: metav1.TypeMeta{
			APIVersion: "kardinal.io/v1alpha1",
			Kind:       "Pipeline",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name:      "nginx-demo",
			Namespace: "default",
		},
		Spec: v1alpha1.PipelineSpec{
			Environments: []v1alpha1.EnvironmentSpec{
				{Name: "test", ApprovalMode: "auto"},
				{Name: "uat", ApprovalMode: "auto"},
				{Name: "prod", ApprovalMode: "pr-review"},
			},
		},
	}

	data, err := json.Marshal(original)
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}

	var got v1alpha1.Pipeline
	if err := json.Unmarshal(data, &got); err != nil {
		t.Fatalf("unmarshal: %v", err)
	}

	if got.Name != original.Name {
		t.Errorf("name: got %q want %q", got.Name, original.Name)
	}
	if len(got.Spec.Environments) != 3 {
		t.Errorf("envs: got %d want 3", len(got.Spec.Environments))
	}
	if got.Spec.Environments[2].ApprovalMode != "pr-review" {
		t.Errorf("approval: got %q want pr-review", got.Spec.Environments[2].ApprovalMode)
	}
}

// TestBundleRoundtrip verifies Bundle JSON roundtrip.
func TestBundleRoundtrip(t *testing.T) {
	original := &v1alpha1.Bundle{
		TypeMeta: metav1.TypeMeta{
			APIVersion: "kardinal.io/v1alpha1",
			Kind:       "Bundle",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name:      "nginx-demo-v1",
			Namespace: "default",
		},
		Spec: v1alpha1.BundleSpec{
			Type:     "image",
			Pipeline: "nginx-demo",
			Images: []v1alpha1.ImageRef{
				{Repository: "ghcr.io/nginx/nginx", Tag: "1.29.0"},
			},
		},
	}

	data, err := json.Marshal(original)
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}

	var got v1alpha1.Bundle
	if err := json.Unmarshal(data, &got); err != nil {
		t.Fatalf("unmarshal: %v", err)
	}

	if got.Spec.Pipeline != "nginx-demo" {
		t.Errorf("pipeline: got %q want nginx-demo", got.Spec.Pipeline)
	}
	if len(got.Spec.Images) != 1 {
		t.Errorf("images: got %d want 1", len(got.Spec.Images))
	}
	if got.Spec.Images[0].Tag != "1.29.0" {
		t.Errorf("tag: got %q want 1.29.0", got.Spec.Images[0].Tag)
	}
}

// TestPolicyGateRoundtrip verifies PolicyGate JSON roundtrip.
func TestPolicyGateRoundtrip(t *testing.T) {
	original := &v1alpha1.PolicyGate{
		TypeMeta: metav1.TypeMeta{
			APIVersion: "kardinal.io/v1alpha1",
			Kind:       "PolicyGate",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name:      "no-weekend-deploys",
			Namespace: "platform-policies",
		},
		Spec: v1alpha1.PolicyGateSpec{
			Expression:      "!schedule.isWeekend",
			Message:         "Production deployments are blocked on weekends",
			RecheckInterval: "5m",
		},
	}

	data, err := json.Marshal(original)
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}

	var got v1alpha1.PolicyGate
	if err := json.Unmarshal(data, &got); err != nil {
		t.Fatalf("unmarshal: %v", err)
	}

	if got.Spec.Expression != "!schedule.isWeekend" {
		t.Errorf("expr: got %q want !schedule.isWeekend", got.Spec.Expression)
	}
	if got.Spec.RecheckInterval != "5m" {
		t.Errorf("recheck: got %q want 5m", got.Spec.RecheckInterval)
	}
}

// TestPromotionStepRoundtrip verifies PromotionStep JSON roundtrip.
func TestPromotionStepRoundtrip(t *testing.T) {
	original := &v1alpha1.PromotionStep{
		TypeMeta: metav1.TypeMeta{
			APIVersion: "kardinal.io/v1alpha1",
			Kind:       "PromotionStep",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name:      "nginx-demo-prod-open-pr",
			Namespace: "default",
		},
		Spec: v1alpha1.PromotionStepSpec{
			PipelineName: "nginx-demo",
			BundleName:   "nginx-demo-v1",
			Environment:  "prod",
			StepType:     "open-pr",
		},
	}

	data, err := json.Marshal(original)
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}

	var got v1alpha1.PromotionStep
	if err := json.Unmarshal(data, &got); err != nil {
		t.Fatalf("unmarshal: %v", err)
	}

	if got.Spec.StepType != "open-pr" {
		t.Errorf("stepType: got %q want open-pr", got.Spec.StepType)
	}
	if got.Spec.Environment != "prod" {
		t.Errorf("env: got %q want prod", got.Spec.Environment)
	}
}

// TestDeepCopy verifies that DeepCopy (generated by controller-gen) produces
// independent copies — a mutation of the copy does not affect the original.
func TestDeepCopy(t *testing.T) {
	orig := &v1alpha1.Pipeline{
		Spec: v1alpha1.PipelineSpec{
			Environments: []v1alpha1.EnvironmentSpec{
				{Name: "test"},
			},
		},
	}

	cp := orig.DeepCopy()
	cp.Spec.Environments[0].Name = "mutated"

	if orig.Spec.Environments[0].Name == "mutated" {
		t.Error("DeepCopy is shallow: mutation of copy affected original")
	}
}

// TestGroupVersion verifies the API group and version constants.
func TestGroupVersion(t *testing.T) {
	if v1alpha1.GroupVersion.Group != "kardinal.io" {
		t.Errorf("group: got %q want kardinal.io", v1alpha1.GroupVersion.Group)
	}
	if v1alpha1.GroupVersion.Version != "v1alpha1" {
		t.Errorf("version: got %q want v1alpha1", v1alpha1.GroupVersion.Version)
	}
}
