apiVersion: kardinal.io/v1alpha1
kind: Pipeline
metadata:
  name: kardinal-test-app
  namespace: default
spec:
  environments:
  - approval: auto
    health:
      resource:
        name: kardinal-test-app
        namespace: kardinal-test-app-test
      type: resource
    name: test
    path: environments/test
    update:
      strategy: kustomize
  - approval: auto
    bake:
      minutes: 10
    health:
      type: argocd
    name: staging
    path: environments/staging
    update:
      strategy: kustomize
  - approval: pr-review
    health:
      timeout: 30m
      type: argoRollouts
    name: prod
    path: environments/prod
    update:
      strategy: kustomize
  git:
    branch: main
    layout: directory
    provider: github
    secretRef:
      name: github-token
    url: https://github.com/pnz1990/kardinal-demo
  historyLimit: 20
