apiVersion: kardinal.io/v1alpha1
kind: Pipeline
metadata:
  name: rollouts-demo
  namespace: default
spec:
  environments:
  - approval: auto
    health:
      type: argocd
    name: test
    path: env/test
    update:
      strategy: kustomize
  - approval: pr-review
    health:
      type: argocd
    name: pre-prod
    path: env/pre-prod
    update:
      strategy: kustomize
  - approval: pr-review
    delivery:
      delegate: argoRollouts
    dependsOn:
    - pre-prod
    health:
      timeout: 30m
      type: argoRollouts
    name: prod-eu
    path: env/prod-eu
    shard: eu-cluster
    update:
      strategy: kustomize
  - approval: pr-review
    delivery:
      delegate: argoRollouts
    dependsOn:
    - pre-prod
    health:
      timeout: 30m
      type: argoRollouts
    name: prod-us
    path: env/prod-us
    shard: us-cluster
    update:
      strategy: kustomize
  git:
    branch: main
    layout: directory
    provider: github
    secretRef:
      name: github-token
    url: https://github.com/myorg/rollouts-demo-deploy
  historyLimit: 20
