//go:build e2e

// Copyright 2026 The kardinal-promoter Authors.
// Licensed under the Apache License, Version 2.0

package live

import (
	"context"
	"fmt"
	"net/http"
	"os"
	"regexp"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	corev1 "k8s.io/api/core/v1"

	v1alpha1 "github.com/kardinal-promoter/kardinal-promoter/api/v1alpha1"
	"github.com/kardinal-promoter/kardinal-promoter/test/e2e/fixtures"
	"github.com/kardinal-promoter/kardinal-promoter/test/e2e/framework"
	"github.com/kardinal-promoter/kardinal-promoter/test/e2e/framework/gitserver"
)

// This file holds the SCM scenarios every git server suite runs. Each
// provider's file (scm_forgejo_test.go, scm_gitea_test.go, scm_gitlab_test.go,
// scm_github_test.go) runs them against its git server and claims its rows;
// the TestSCM_ tests here run in every suite.

// The headers /webhook/scm reads a signature from, in the order it looks for
// them (cmd/kardinal-controller/webhook.go).
const (
	hubSignature     = "X-Hub-Signature-256"
	giteaSignature   = "X-Gitea-Signature"
	forgejoSignature = "X-Forgejo-Signature"
	gitlabToken      = "X-Gitlab-Token"
)

// envSCMAPI is the git server's API URL as the controller reaches it, which
// hack/e2e/up.sh passes as --scm-api-url (unset on GitHub).
const envSCMAPI = "KARDINAL_E2E_SCM_API"

// fakeToken is a token no git server accepts. It is not a secret.
const fakeToken = "kardinal-e2e-not-a-token"

// prBodyFooter ends every PR body (pkg/scm/pr_template.go).
const prBodyFooter = "---\n*Generated by [kardinal-promoter](https://github.com/pnz1990/kardinal-promoter)*"

// Rows of the PR body (pkg/scm/pr_template.go).
var (
	evaluatedAt = `\d{4}-\d\d-\d\dT\d\d:\d\dZ`
	upstreamRow = regexp.MustCompile(`\| test \| ` + evaluatedAt + ` \| \d+m \|`)
)

// requireKind fails a provider test run against another suite's git server.
func requireKind(t *testing.T, e *framework.Env, kind string) {
	t.Helper()
	if got := e.Git.Kind(); got != kind {
		t.Fatalf("this test is for %s; the suite's git server is %s (check the suite's RUN pattern)", kind, got)
	}
}

// waitOpenPR waits until bundle's env step waits for its PR and returns the
// step and the open PR.
func (a *app) waitOpenPR(t *testing.T, bundle, env string) (*v1alpha1.PromotionStep, gitserver.PR) {
	t.Helper()
	ps := a.e.WaitStepState(t, a.ns, pipelineName, bundle, env, "WaitingForMerge", promoteTimeout)
	return ps, a.openPR(t, bundle, env)
}

// rerunOpenPR rewinds a step that waits for its PR to open-pr, as if the
// controller had crashed before saving the PR, and waits until open-pr ran
// again and the step waits for a PR again.
func (a *app) rerunOpenPR(t *testing.T, ps *v1alpha1.PromotionStep, bundle, env string) *v1alpha1.PromotionStep {
	t.Helper()
	rewound := time.Now().Truncate(time.Second)
	idx := a.e.RewindToOpenPR(t, ps)
	return a.e.WaitStep(t, a.ns, pipelineName, bundle, env, 2*time.Minute, "open-pr to run again",
		func(ps *v1alpha1.PromotionStep) (bool, string) {
			if len(ps.Status.Steps) <= idx {
				return false, fmt.Sprintf("%d steps", len(ps.Status.Steps))
			}
			s := ps.Status.Steps[idx]
			done := s.CompletedAt != nil && !s.CompletedAt.Time.Before(rewound)
			return done && ps.Status.State == "WaitingForMerge",
				fmt.Sprintf("state=%q open-pr=%s message=%q", ps.Status.State, s.State, ps.Status.Message)
		})
}

// controllerArgs are the args of the running controller container.
func controllerArgs(t *testing.T, e *framework.Env) []string {
	t.Helper()
	pod := e.ControllerPod(t)
	for _, c := range pod.Spec.Containers {
		if c.Name == framework.ControllerContainer {
			return c.Args
		}
	}
	t.Fatalf("controller pod %s has no %s container", pod.Name, framework.ControllerContainer)
	return nil
}

// kindSignature is the header the git server of kind signs its webhook
// deliveries in.
func kindSignature(kind string) string {
	switch kind {
	case "gitlab":
		return gitlabToken
	case "github":
		return hubSignature
	case "gitea":
		return giteaSignature
	}
	return forgejoSignature
}

// eventHeader is the event header that goes with signature header sig.
func eventHeader(sig string) string {
	switch sig {
	case gitlabToken:
		return "X-Gitlab-Event"
	case hubSignature:
		return "X-GitHub-Event"
	case giteaSignature:
		return "X-Gitea-Event"
	}
	return "X-Forgejo-Event"
}

// prEvent is the pull request event name in eventHeader(sig).
func prEvent(sig string) string {
	if sig == gitlabToken {
		return "Merge Request Hook"
	}
	return "pull_request"
}

// signature is header sig's value for body: GitLab's plaintext token, GitHub's
// "sha256=" HMAC, or the hex HMAC of Gitea and Forgejo.
func signature(sig, secret string, body []byte) string {
	switch sig {
	case gitlabToken:
		return secret
	case hubSignature:
		return "sha256=" + framework.HMACHex(secret, body)
	}
	return framework.HMACHex(secret, body)
}

// signedPREvent are the headers of a pull request event signed with secret
// in sig.
func signedPREvent(sig, secret string, body []byte) map[string]string {
	return map[string]string{sig: signature(sig, secret, body), eventHeader(sig): prEvent(sig)}
}

// forgejoEvent is a Forgejo/Gitea pull request event body.
func forgejoEvent(t *testing.T, repo string, number int, action string, merged bool, state string) []byte {
	t.Helper()
	return framework.JSONBody(t, map[string]interface{}{
		"action": action,
		"number": number,
		"pull_request": map[string]interface{}{
			"number": number, "merged": merged, "state": state,
		},
		"repository": map[string]interface{}{"full_name": repo},
	})
}

// mergedEvent is the body kind's git server sends when PR number of repo
// is merged; sha is the merge commit the event carries, "" for an event
// without one (a GitLab fast-forward merge).
func mergedEvent(t *testing.T, kind, repo string, number int, sha string) []byte {
	t.Helper()
	switch kind {
	case "gitlab":
		return framework.JSONBody(t, map[string]interface{}{
			"object_kind": "merge_request",
			"object_attributes": map[string]interface{}{
				"iid": number, "state": "merged", "action": "merge", "merge_commit_sha": sha,
			},
			"project": map[string]interface{}{"path_with_namespace": repo},
		})
	case "github":
		return framework.JSONBody(t, map[string]interface{}{
			"action":       "closed",
			"pull_request": map[string]interface{}{"number": number, "merged": true, "merge_commit_sha": sha},
			"repository":   map[string]interface{}{"full_name": repo},
		})
	}
	if sha == "" {
		return forgejoEvent(t, repo, number, "closed", true, "closed")
	}
	return framework.JSONBody(t, map[string]interface{}{
		"action": "closed",
		"number": number,
		"pull_request": map[string]interface{}{
			"number": number, "merged": true, "state": "closed", "merge_commit_sha": sha,
		},
		"repository": map[string]interface{}{"full_name": repo},
	})
}

// mergeSeenByWebhook merges pr right after the PRStatus reconciler polled it,
// has deliver post the merge event (nil: the git server's own webhook
// delivers it), and returns the controller's "marked merged via webhook" line.
// The next poll is about 30s away, so the line, with no poll that saw the
// merge before it, shows the webhook told the controller.
func (a *app) mergeSeenByWebhook(t *testing.T, ps *v1alpha1.PromotionStep, pr gitserver.PR,
	deliver func(*v1alpha1.PRStatus)) framework.LogLine {
	t.Helper()
	var prs *v1alpha1.PRStatus
	framework.Eventually(t, time.Minute, fmt.Sprintf("the PRStatus to poll PR #%d", pr.Number), func(ctx context.Context) (bool, string) {
		p, err := a.e.PRStatusOf(ctx, ps)
		if err != nil {
			return false, err.Error()
		}
		prs = p
		return p.Spec.PRNumber == pr.Number && p.Status.LastCheckedAt != nil, framework.DescribePRStatus(p)
	})
	ref := prs.Name
	polled := framework.LogMessage("PR still open, requeueing", "prstatus", ref, "namespace", a.ns)
	a.e.ControllerLog(time.Now().Add(-40*time.Second)).Wait(t, time.Minute, "a poll of "+ref+" in the last 10s",
		func(l framework.LogLine) bool { return polled(l) && time.Since(l.At) < 10*time.Second })

	since := time.Now()
	a.merge(t, pr)
	if deliver != nil {
		deliver(prs)
	}
	mark := a.e.WaitControllerLog(t, since, 25*time.Second, "the webhook to mark "+ref+" merged",
		framework.LogMessage("PRStatus marked merged via webhook", "prstatus", ref, "namespace", a.ns, "pr", strconv.Itoa(pr.Number)))
	received := framework.LogMessage("webhook received", "pr", strconv.Itoa(pr.Number), "merged", "true")
	a.e.WaitControllerLog(t, since, 5*time.Second, "the merge event of "+prs.Spec.Repo+" logged with its repo",
		func(l framework.LogLine) bool { return received(l) && strings.EqualFold(l.Str("repo"), prs.Spec.Repo) })
	for _, l := range a.e.ControllerLogLines(t, since, framework.LogMessage("PR merged — status updated", "prstatus", ref, "namespace", a.ns)) {
		assert.False(t, l.At.Before(mark.At), "a poll saw the merge before the webhook: %s", l)
	}
	return mark
}

// mergeByWebhook merges bundle's env PR and checks that the webhook told the
// controller: header "" relies on the git server's own delivery; otherwise
// the test posts the merge event signed in header. eventSHA says whether the
// event carries the merge commit; when it does not, the PRStatus reconciler
// asks the git server for it. The step then reaches Verified with the merge
// commit as the revision it checked.
func (a *app) mergeByWebhook(t *testing.T, bundle, env, header string, eventSHA bool) {
	t.Helper()
	ps, pr := a.waitOpenPR(t, bundle, env)
	var deliver func(*v1alpha1.PRStatus)
	if header != "" {
		deliver = func(prs *v1alpha1.PRStatus) {
			sha := ""
			if eventSHA {
				sha = a.e.WaitPRState(t, a.repo, pr.Number, "merged", 30*time.Second).MergeCommit
			}
			body := mergedEvent(t, a.e.Git.Kind(), prs.Spec.Repo, pr.Number, sha)
			code := a.e.PostSCMWebhook(t, signedPREvent(header, framework.WebhookSecret(t), body), body)
			require.Equal(t, http.StatusNoContent, code, "the merge event signed in %s", header)
		}
	}
	mark := a.mergeSeenByWebhook(t, ps, pr, deliver)

	merged := a.e.WaitPRState(t, a.repo, pr.Number, "merged", 30*time.Second)
	require.NotEmpty(t, merged.MergeCommit, "the git server reports PR #%d's merge commit", pr.Number)
	if eventSHA {
		assert.Equal(t, merged.MergeCommit, mark.Str("mergeCommit"), "the webhook records the event's merge commit")
	} else {
		assert.Empty(t, mark.Str("mergeCommit"), "the event carries no merge commit")
	}
	prs := a.e.WaitPRStatus(t, a.ns, pipelineName, bundle, env, time.Minute, "merged with its merge commit",
		func(p *v1alpha1.PRStatus) bool { return p.Status.Merged && p.Status.MergeCommitSHA != "" })
	assert.Equal(t, merged.MergeCommit, prs.Status.MergeCommitSHA)
	done := a.e.WaitStepState(t, a.ns, pipelineName, bundle, env, "Verified", promoteTimeout)
	assert.Equal(t, merged.MergeCommit, done.Status.Outputs["mergeCommitSHA"], "the revision the health check expected")
}

// stillOpen checks for d that bundle's env step still waits for its PR and
// the PRStatus still records it open and not merged.
func (a *app) stillOpen(t *testing.T, bundle, env string, d time.Duration, why string) {
	t.Helper()
	framework.Consistently(t, d, why+": the step waits for the open PR", func(context.Context) (bool, string) {
		// Not the poll context, which ends at the deadline.
		ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
		defer cancel()
		ps, ok, err := a.e.Step(ctx, a.ns, pipelineName, bundle, env)
		if err != nil || !ok {
			return false, fmt.Sprintf("step: ok=%v err=%v", ok, err)
		}
		prs, err := a.e.PRStatusOf(ctx, ps)
		if err != nil {
			return false, err.Error()
		}
		return ps.Status.State == "WaitingForMerge" && prs.Status.Open && !prs.Status.Merged,
			fmt.Sprintf("state=%q %s", ps.Status.State, framework.DescribePRStatus(prs))
	})
}

// prBody is a PR body with the line endings the template wrote (GitLab
// returns CRLF) and without the trailing newline.
func prBody(raw string) string {
	return strings.TrimSpace(strings.ReplaceAll(raw, "\r\n", "\n"))
}

// scmPromotionPR checks the PR a pr-review environment opens, then reruns
// open-pr and checks it finds that PR instead of opening another. edit, when
// set, changes the Pipeline first.
func scmPromotionPR(t *testing.T, e *framework.Env, edit func(*v1alpha1.Pipeline)) {
	t.Helper()
	a := newArgoApp(t, e, "test", "prod")
	e.CreateGate(t, framework.Gate(a.ns, "always", "prod", "true", recheck))
	p := a.pipeline(map[string]string{"prod": "pr-review"})
	if edit != nil {
		edit(p)
	}
	a.apply(t, p)

	bundle := e.CreateBundle(t, a.ns, pipelineName, "--image", imageV2)
	e.WaitStepState(t, a.ns, pipelineName, bundle, "test", "Verified", promoteTimeout)
	ps, pr := a.waitOpenPR(t, bundle, "prod")

	assert.Equal(t, "[kardinal] Promote "+bundle+" to prod", pr.Title)
	assert.Equal(t, prHead(bundle, "prod"), pr.Head)
	assert.Equal(t, a.repo.Branch, pr.Base)
	assert.Subset(t, pr.Labels, []string{"kardinal", "kardinal/promotion"})
	assert.NotContains(t, pr.Labels, "kardinal/rollback")
	body := prBody(pr.Body)
	assert.True(t, strings.HasPrefix(body, "<!-- kardinal-promoter auto-generated PR -->\n## Promotion: "+bundle+" -> podinfo/prod\n"),
		"body starts with the promotion heading:\n%s", body)
	assert.Contains(t, body, "| "+fixtures.Image+" | "+fixtures.V2+" | — | — | — | — |", "artifact row")
	assert.Regexp(t, `\| always \| `+regexp.QuoteMeta(a.ns)+` \| Pass \| bundle\.version=`+regexp.QuoteMeta(fixtures.V2)+
		`: true = true \| `+evaluatedAt+` \|`, body, "gate row")
	assert.Regexp(t, upstreamRow, body, "upstream row")
	assert.True(t, strings.HasSuffix(body, prBodyFooter), "body ends with the footer:\n%s", body)

	ps = a.rerunOpenPR(t, ps, bundle, "prod")
	assert.Equal(t, strconv.Itoa(pr.Number), ps.Status.Outputs["prNumber"], "open-pr found PR #%d again", pr.Number)
	prs, err := e.Git.PullRequests(context.Background(), a.repo)
	require.NoError(t, err)
	var same []string
	for _, p := range prs {
		if p.Head == pr.Head {
			same = append(same, fmt.Sprintf("#%d %s", p.Number, p.State))
		}
	}
	assert.Equal(t, []string{fmt.Sprintf("#%d open", pr.Number)}, same, "PRs from %s", pr.Head)

	a.merge(t, pr)
	e.WaitStepState(t, a.ns, pipelineName, bundle, "prod", "Verified", promoteTimeout)
	assertEnvAt(t, a, "prod", fixtures.V2)
}

// scmMergeByPolling merges a PR on a repo without the webhook and checks the
// PRStatus poll finds the merge and its commit within one interval, and the
// step goes on to HealthChecking and Verified with that commit. check, when
// set, runs while the PR is open.
func scmMergeByPolling(t *testing.T, e *framework.Env, check func(a *app, bundle string, ps *v1alpha1.PromotionStep, pr gitserver.PR)) {
	t.Helper()
	a := newArgoAppIn(t, e, e.RepoWithoutWebhook, "test", "prod")
	a.apply(t, a.pipeline(map[string]string{"prod": "pr-review"}))
	bundle := e.CreateBundle(t, a.ns, pipelineName, "--image", imageV2)
	ps, pr := a.waitOpenPR(t, bundle, "prod")
	if check != nil {
		check(a, bundle, ps, pr)
	}

	ref := ps.Spec.PRStatusRef
	since := time.Now()
	a.merge(t, pr)
	polled := e.WaitControllerLog(t, since, 90*time.Second, "the poll that finds PR #"+strconv.Itoa(pr.Number)+" merged",
		framework.LogMessage("PR merged — status updated", "prstatus", ref, "namespace", a.ns))
	assert.WithinDuration(t, since, polled.At, 45*time.Second, "PRStatus polls an open PR every 30s")
	e.WaitControllerLog(t, since, time.Minute, "the step to leave WaitingForMerge",
		framework.LogMessage("PRStatus reports merged — advancing to HealthChecking", "prStatusRef", ref))

	merged := e.WaitPRState(t, a.repo, pr.Number, "merged", 30*time.Second)
	require.NotEmpty(t, merged.MergeCommit)
	assert.Equal(t, merged.MergeCommit, polled.Str("mergeCommit"), "the poll records the merge commit")
	done := e.WaitStepState(t, a.ns, pipelineName, bundle, "prod", "Verified", promoteTimeout)
	prs, err := e.PRStatusOf(context.Background(), done)
	require.NoError(t, err)
	assert.True(t, prs.Status.Merged)
	assert.Equal(t, merged.MergeCommit, prs.Status.MergeCommitSHA)
	assert.Equal(t, merged.MergeCommit, done.Status.Outputs["mergeCommitSHA"], "the revision the health check expected")
	assert.Empty(t, e.ControllerLogLines(t, since, framework.LogMessage("PRStatus marked merged via webhook", "prstatus", ref)),
		"the repo has no webhook")
	assertEnvAt(t, a, "prod", fixtures.V2)
}

// scmBadSignature opens a PR, posts its merge event with a wrong signature
// and without one in each of headers, and checks each is refused with 401
// and changes nothing. The same event for another repo, signed right, is
// accepted, so the 401s are the signature's. It returns the app with the PR
// still open, and its PRStatus.
func scmBadSignature(t *testing.T, e *framework.Env, headers ...string) (*app, string, gitserver.PR, *v1alpha1.PRStatus) {
	t.Helper()
	a, bundle, pr, prs := prOpenWithoutWebhook(t, e)
	kind := e.Git.Kind()
	secret := framework.WebhookSecret(t)
	body := mergedEvent(t, kind, prs.Spec.Repo, pr.Number, pr.HeadSHA)
	for i, h := range headers {
		assert.Equal(t, http.StatusUnauthorized, e.PostSCMWebhook(t, signedPREvent(h, "not-the-secret", body), body),
			"%s signed with another secret", h)
		assert.Equal(t, http.StatusUnauthorized, e.PostSCMWebhook(t, map[string]string{eventHeader(h): prEvent(h)}, body),
			"no %s", h)
		control := mergedEvent(t, kind, "e2e/no-such-repo", 900000+100*pr.Number+i, pr.HeadSHA)
		assert.Equal(t, http.StatusNoContent, e.PostSCMWebhook(t, signedPREvent(h, secret, control), control),
			"another repo's merge event signed right in %s", h)
	}
	a.stillOpen(t, bundle, "prod", 10*time.Second, "after the refused merge events")
	return a, bundle, pr, prs
}

// prOpenWithoutWebhook opens a prod PR on a repo without the webhook, so only
// the test's events reach the controller, and waits until its PRStatus tracks
// it open. It returns the app, the Bundle, the PR and the PRStatus.
func prOpenWithoutWebhook(t *testing.T, e *framework.Env) (*app, string, gitserver.PR, *v1alpha1.PRStatus) {
	t.Helper()
	a := newArgoAppIn(t, e, e.RepoWithoutWebhook, "prod")
	a.apply(t, a.pipeline(map[string]string{"prod": "pr-review"}))
	bundle := e.CreateBundle(t, a.ns, pipelineName, "--image", imageV2)
	_, pr := a.waitOpenPR(t, bundle, "prod")
	prs := e.WaitPRStatus(t, a.ns, pipelineName, bundle, "prod", time.Minute, "tracking the open PR",
		func(p *v1alpha1.PRStatus) bool { return p.Spec.PRNumber == pr.Number && p.Status.Open })
	return a, bundle, pr, prs
}

// scmClosesPRs checks the two ways kardinal closes its PR: a newer Bundle
// supersedes the older one's open PR, and waitForMergeTimeout fails the step
// and closes its PR. Each PR is closed unmerged with one comment saying why,
// and its head branch kardinal/<bundle>/prod is deleted, so neither can be
// merged later. GitHub's merge API merges a closed PR whose branch is still
// there; with the branch gone it refuses, as the other servers do.
func scmClosesPRs(t *testing.T, e *framework.Env) {
	t.Helper()
	a := newArgoApp(t, e, "prod")
	p := a.pipeline(map[string]string{"prod": "pr-review"})
	envSpec(t, p, "prod").WaitForMergeTimeout = "90s"
	a.apply(t, p)

	older := e.CreateBundle(t, a.ns, pipelineName, "--image", imageV2)
	_, pr1 := a.waitOpenPR(t, older, "prod")
	newer := e.CreateBundle(t, a.ns, pipelineName, "--image", imageV3)
	ps := e.WaitStepState(t, a.ns, pipelineName, older, "prod", "Failed", time.Minute)
	assert.Contains(t, ps.Status.Message, "bundle "+older+" was superseded")
	e.WaitPRState(t, a.repo, pr1.Number, "closed", time.Minute)
	oneComment(t, a, pr1.Number, "kardinal closed this PR: bundle "+older+" was superseded")

	_, pr2 := a.waitOpenPR(t, newer, "prod")
	ps = e.WaitStepState(t, a.ns, pipelineName, newer, "prod", "Failed", 3*time.Minute+30*time.Second)
	assert.Contains(t, ps.Status.Message, "wait-for-merge timeout after 1m30s")
	e.WaitPRState(t, a.repo, pr2.Number, "closed", time.Minute)
	oneComment(t, a, pr2.Number, "kardinal closed this PR: it was not merged within waitForMergeTimeout (1m30s)")

	for _, c := range []struct {
		bundle string
		pr     int
	}{{older, pr1.Number}, {newer, pr2.Number}} {
		head := prHead(c.bundle, "prod")
		framework.Eventually(t, time.Minute, fmt.Sprintf("PR #%d's branch %s deleted", c.pr, head),
			func(ctx context.Context) (bool, string) {
				_, err := e.Brancher(t).BranchHead(ctx, a.repo, head)
				return gitserver.IsNotFound(err), fmt.Sprintf("err=%v", err)
			})
		ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
		assert.Error(t, e.Git.MergePR(ctx, a.repo, c.pr), "closed PR #%d cannot be merged", c.pr)
		cancel()
		e.WaitPRState(t, a.repo, c.pr, "closed", 30*time.Second) // not merged
	}
	assertEnvAt(t, a, "prod", fixtures.V1)
}

// oneComment waits until PR number has a comment containing substr and
// checks it has exactly one.
func oneComment(t *testing.T, a *app, number int, substr string) {
	t.Helper()
	framework.Eventually(t, time.Minute, fmt.Sprintf("PR #%d's comment %q", number, substr), func(context.Context) (bool, string) {
		n := len(a.e.PRComments(t, a.repo, number, substr))
		return n > 0, fmt.Sprintf("%d comments", n)
	})
	assert.Len(t, a.e.PRComments(t, a.repo, number, substr), 1, "PR #%d: one comment %q", number, substr)
}

// scmApprovals checks that the PRStatus reads the PR's approvals and a gate
// on bundle.pr sees them: false and 0 before the review, true and 1 after.
func scmApprovals(t *testing.T, e *framework.Env) {
	t.Helper()
	reviewer, ok := e.Git.(gitserver.Reviewer)
	require.True(t, ok, "the suite's git server %T cannot review PRs", e.Git)
	a, bundle, pr := scmUnreviewed(t, e)

	require.NoError(t, reviewer.ApprovePR(context.Background(), a.repo, pr.Number, "e2e: approved"))
	waitPRApproved(t, e, a.ns, bundle, "staging", 1)
	a.merge(t, pr)
	e.WaitStepState(t, a.ns, pipelineName, bundle, "staging", "Verified", promoteTimeout)
	e.WaitGateReady(t, a.ns, bundle, "prod", "staging-approved", true, "= true", gateTimeout)
	e.WaitStepState(t, a.ns, pipelineName, bundle, "prod", "Verified", promoteTimeout)
	assertEnvAt(t, a, "prod", fixtures.V2)
}

// scmUnreviewed opens the PR of pr-review environment staging, which no one
// reviews, under gate staging-approved, which lets prod promote once
// bundle.pr["staging"] is approved. Its poll reads the PR's reviews: the
// PRStatus says not approved with no approvals, and the controller logs no
// failed review read, which would keep the PRStatus's previous values. The
// gate holds prod. It returns the app, the Bundle and the PR.
func scmUnreviewed(t *testing.T, e *framework.Env) (*app, string, gitserver.PR) {
	t.Helper()
	a := newArgoApp(t, e, "staging", "prod")
	e.CreateGate(t, framework.Gate(a.ns, "staging-approved", "prod",
		`"staging" in bundle.pr && bundle.pr["staging"].isApproved && bundle.pr["staging"].approvalCount >= 1`, recheck))
	a.apply(t, a.pipeline(map[string]string{"staging": "pr-review"}))

	since := time.Now()
	bundle := e.CreateBundle(t, a.ns, pipelineName, "--image", imageV2)
	_, pr := a.waitOpenPR(t, bundle, "staging")
	prs := e.WaitPRStatus(t, a.ns, pipelineName, bundle, "staging", time.Minute, "polled",
		func(p *v1alpha1.PRStatus) bool { return p.Spec.PRNumber == pr.Number && p.Status.LastCheckedAt != nil })
	assert.False(t, prs.Status.Approved, "not approved before the review")
	assert.Zero(t, prs.Status.ApprovalCount)
	assert.Empty(t, e.ControllerLog(since).Lines(t,
		framework.LogMessage("GetPRReviewStatus failed", "prstatus", prs.Name, "namespace", a.ns)),
		"the poll read the PR's reviews")
	e.WaitGateReady(t, a.ns, bundle, "prod", "staging-approved", false, "= false", gateTimeout)
	return a, bundle, pr
}

// scmRejectedToken starts a controller variant with a token the git server
// rejects and checks the startup token check warns and the variant still
// serves (ControllerVariantSpec waits for it).
func scmRejectedToken(t *testing.T, e *framework.Env, ns string) {
	t.Helper()
	since := time.Now()
	v := e.ControllerVariantSpec(t, ns, "a GITHUB_TOKEN the git server rejects", func(spec *corev1.PodSpec) {
		framework.SetEnv(spec, "GITHUB_TOKEN", &corev1.EnvVar{Name: "GITHUB_TOKEN", Value: fakeToken})
	})
	l := e.VariantLog(v, since).Wait(t, time.Minute, "the token scope warning",
		framework.LogMessage("SCM TOKEN SCOPE WARNING", "provider", e.Git.Kind(), "missing_scope", "<valid token>"))
	assert.NotEmpty(t, l.Str("consequence"))
}

// scmTokenNotChecked starts a controller variant with the suite's token and
// checks the startup token check reports that the git server accepted it
// but cannot show its scopes (Forgejo and Gitea).
func scmTokenNotChecked(t *testing.T, e *framework.Env, ns string) {
	t.Helper()
	since := time.Now()
	v := e.ControllerVariant(t, ns, nil)
	e.VariantLog(v, since).Wait(t, time.Minute, "the token check to accept the token",
		framework.LogMessage("SCM token scopes not checked", "provider", e.Git.Kind()))
	assert.Empty(t, e.VariantLog(v, since).Lines(t, framework.LogMessage("SCM TOKEN SCOPE WARNING")), "no warning for a valid token")
}

// scmAPIURL checks that the controller runs with --scm-api-url set to the
// suite's git server and promotes through it, and that a variant with the
// flag pointed elsewhere calls that host.
func scmAPIURL(t *testing.T, e *framework.Env) {
	t.Helper()
	api := os.Getenv(envSCMAPI)
	require.NotEmpty(t, api, "%s is set by the suite's git server component", envSCMAPI)
	assert.Contains(t, controllerArgs(t, e), "--scm-api-url="+api)
	a := scmPRFlow(t, e)
	scmBogusAPI(t, e, a.ns)
}

// scmPRFlow promotes a Bundle through one pr-review environment, merging its
// PR, and returns the app.
func scmPRFlow(t *testing.T, e *framework.Env) *app {
	t.Helper()
	a := newArgoApp(t, e, "prod")
	a.apply(t, a.pipeline(map[string]string{"prod": "pr-review"}))
	bundle := e.CreateBundle(t, a.ns, pipelineName, "--image", imageV2)
	_, pr := a.waitOpenPR(t, bundle, "prod")
	a.merge(t, pr)
	e.WaitStepState(t, a.ns, pipelineName, bundle, "prod", "Verified", promoteTimeout)
	assertEnvAt(t, a, "prod", fixtures.V2)
	return a
}

// noSCMHost resolves nowhere (.invalid is reserved).
const noSCMHost = "kardinal-e2e-no-scm.invalid"

// scmBogusAPI starts a controller variant with --scm-api-url on a host that
// does not exist and checks its startup token check called that host.
func scmBogusAPI(t *testing.T, e *framework.Env, ns string) {
	t.Helper()
	since := time.Now()
	v := e.ControllerVariantSpec(t, ns, "--scm-api-url=http://"+noSCMHost, func(spec *corev1.PodSpec) {
		framework.SetArg(spec, "scm-api-url", "http://"+noSCMHost)
	})
	l := e.VariantLog(v, since).Wait(t, time.Minute, "the token check to call "+noSCMHost,
		framework.LogMessage("SCM token scope check skipped", "provider", e.Git.Kind()))
	assert.Contains(t, l.Str("error"), noSCMHost)
}

// scmLabels checks the PR labels on a promotion and a rollback: a promotion
// PR gets kardinal and kardinal/promotion, and the PR of a `kardinal
// rollback` gets kardinal/rollback too, with the rollback title and body. It
// merges every PR and returns the app, whose prod runs fixtures.V2.
func scmLabels(t *testing.T, e *framework.Env) *app {
	t.Helper()
	a := newArgoApp(t, e, "prod")
	a.apply(t, a.pipeline(map[string]string{"prod": "pr-review"}))
	labels := []string{"kardinal", "kardinal/promotion"}

	first := e.CreateBundle(t, a.ns, pipelineName, "--image", imageV2)
	_, pr := a.waitOpenPR(t, first, "prod")
	assert.Subset(t, pr.Labels, labels)
	assert.NotContains(t, pr.Labels, "kardinal/rollback")
	a.merge(t, pr)
	e.WaitStepState(t, a.ns, pipelineName, first, "prod", "Verified", promoteTimeout)
	second := e.CreateBundle(t, a.ns, pipelineName, "--image", imageV3)
	_, pr = a.waitOpenPR(t, second, "prod")
	a.merge(t, pr)
	e.WaitStepState(t, a.ns, pipelineName, second, "prod", "Verified", promoteTimeout)

	out := e.MustKardinal(t, a.ns, "rollback", pipelineName, "--env", "prod")
	m := regexp.MustCompile(`Bundle (\S+) created \(rollbackOf=(\S+)\)`).FindStringSubmatch(out)
	require.NotNil(t, m, "rollback output:\n%s", out)
	rollback := m[1]
	require.Equal(t, first, m[2], "rolls back to the Bundle before %s", second)
	_, pr = a.waitOpenPR(t, rollback, "prod")
	assert.Equal(t, "[kardinal] Rollback prod to "+rollback+" (restores "+fixtures.V2+")", pr.Title)
	assert.Subset(t, pr.Labels, append(labels, "kardinal/rollback"))
	body := prBody(pr.Body)
	assert.True(t, strings.HasPrefix(body, "<!-- kardinal-promoter auto-generated PR -->\n## ROLLBACK: "+rollback+" -> podinfo/prod\n\n"+
		"> **This is a rollback PR.** It restores the images of bundle "+first+" in environment prod.\n"+
		"> Rolling back FROM: "+second+" ("+fixtures.V3+")\n"+
		"> Rolling back TO: "+first+" ("+fixtures.V2+")\n"+
		"> Rolled back by: "+cliUser(t)+"\n"), "rollback body:\n%s", body)
	a.merge(t, pr)
	e.WaitStepState(t, a.ns, pipelineName, rollback, "prod", "Verified", promoteTimeout)
	assertEnvAt(t, a, "prod", fixtures.V2)
	return a
}

// scmLabelsAndRotation checks the PR labels on a promotion and a rollback
// (scmLabels), then rotates the token to a git user that may push and open
// PRs but not label them: the running controller picks the new token up from
// the Secret without a restart, opens the next PR as that user, and leaves it
// open without labels. The test must not be parallel: it changes the
// controller's token.
func scmLabelsAndRotation(t *testing.T, e *framework.Env, scopes []string) {
	t.Helper()
	a := scmLabels(t, e)

	// The new token's user may push and open PRs but not label them.
	user := "rot-" + a.ns[len(a.ns)-8:]
	tok := e.GitUser(t, user, scopes)
	require.NoError(t, e.GitUsers(t).AddCollaborator(context.Background(), a.repo, user))
	pod := e.ControllerPod(t).Name
	since := time.Now()
	restoreSCM := e.SetSecretValue(t, framework.ControllerNamespace, framework.GitSecretName, "token", []byte(tok))
	restoreGit := e.SetSecretValue(t, a.ns, framework.GitSecretName, "token", []byte(tok))
	rotated := framework.LogMessage("SCM credentials rotated", "secret", framework.ControllerNamespace+"/"+framework.GitSecretName, "key", "token")
	e.WaitControllerLog(t, since, 50*time.Second, "the controller to load the new token", rotated)
	assert.Equal(t, pod, e.ControllerPod(t).Name, "no restart")

	fourth := e.CreateBundle(t, a.ns, pipelineName, "--image", imageV3)
	_, pr := a.waitOpenPR(t, fourth, "prod")
	assert.Equal(t, user, pr.Author, "the PR is opened with the new token")
	assert.Empty(t, pr.Labels, "the new token may not label PRs")
	e.WaitControllerLog(t, since, time.Minute, "the label failure",
		framework.LogMessage("add PR labels failed", "pr", strconv.Itoa(pr.Number)))
	// The step message records the failure while the step waits for the merge
	// (docs/pr-evidence.md), and status.outputs.prLabelsError keeps it.
	want := fmt.Sprintf("PR #%d is open, waiting for merge; adding labels failed: ", pr.Number)
	ps := e.WaitStep(t, a.ns, pipelineName, fourth, "prod", time.Minute, "the label failure in its message",
		func(s *v1alpha1.PromotionStep) (bool, string) {
			return s.Status.State == "WaitingForMerge" && strings.HasPrefix(s.Status.Message, want),
				fmt.Sprintf("state=%q message=%q", s.Status.State, s.Status.Message)
		})
	assert.NotEmpty(t, ps.Status.Outputs["prLabelsError"], "status.outputs.prLabelsError")
	a.stillOpen(t, fourth, "prod", 10*time.Second, "after the label failure")

	since = time.Now()
	restoreSCM()
	restoreGit()
	e.WaitControllerLog(t, since, 50*time.Second, "the controller to load the old token again", rotated)
	a.merge(t, pr)
	e.WaitStepState(t, a.ns, pipelineName, fourth, "prod", "Verified", promoteTimeout)
	assertEnvAt(t, a, "prod", fixtures.V3)
}

// TestSCM_DeletedStepTracksItsNewPR deletes, on its own, the prod
// PromotionStep of a Bundle waiting for its PR. The controller closes that PR
// with a comment, kro creates the step again, and the new step opens a new PR.
// Its PRStatus kept naming the old PR, so the controller polled the closed PR,
// never saw a merge of the new one, and failed the new step when the 5-minute
// grace window ended (B72). Now the PRStatus names the new PR, with a status
// written for it, and merging the new PR promotes prod. The new PR is opened
// from the same branch about a second after the delete; the controller deleted
// that branch with the old PR, and Forgejo and Gitea close every open PR of a
// deleted branch from a queue after the delete returns, so they closed the new
// PR too (B79). The controller keeps the branch now, and the new PR stays open
// until it is merged.
//
// Covers STEP-DELETE-PR-04.
func TestSCM_DeletedStepTracksItsNewPR(t *testing.T) {
	t.Parallel()
	e := framework.New(t)
	ctx := context.Background()
	a := newArgoApp(t, e, "prod")
	a.apply(t, a.pipeline(map[string]string{"prod": "pr-review"}))
	bundle := e.CreateBundle(t, a.ns, pipelineName, "--image", imageV2)
	old, pr := a.waitOpenPR(t, bundle, "prod")
	require.Contains(t, old.Finalizers, closePRFinalizer, "the step closes its PR when it is deleted")
	e.WaitPRStatus(t, a.ns, pipelineName, bundle, "prod", time.Minute, fmt.Sprintf("tracking PR #%d", pr.Number),
		func(p *v1alpha1.PRStatus) bool { return p.Spec.PRNumber == pr.Number && p.Status.Open })

	require.NoError(t, e.Client.Delete(ctx, old))
	e.WaitPRState(t, a.repo, pr.Number, "closed", 2*time.Minute)
	oneComment(t, a, pr.Number, "kardinal closed this PR: PromotionStep "+old.Name+" was deleted")

	e.WaitStep(t, a.ns, pipelineName, bundle, "prod", promoteTimeout, "the recreated step waiting for a new PR",
		func(s *v1alpha1.PromotionStep) (bool, string) {
			return s.UID != old.UID && s.Status.State == "WaitingForMerge",
				fmt.Sprintf("uid=%s state=%q message=%q", s.UID, s.Status.State, s.Status.Message)
		})
	again := a.openPR(t, bundle, "prod")
	require.NotEqual(t, pr.Number, again.Number, "the recreated step opened a new PR")
	require.Equal(t, pr.Head, again.Head, "the new PR is from the old PR's branch")
	e.WaitPRStatus(t, a.ns, pipelineName, bundle, "prod", time.Minute, fmt.Sprintf("tracking the new PR #%d", again.Number),
		func(p *v1alpha1.PRStatus) bool {
			return p.Spec.PRNumber == again.Number && p.Status.ObservedGeneration == p.Generation &&
				p.Status.Open && !p.Status.ClosedFinal && p.Status.ClosedAt == nil
		})

	a.merge(t, again)
	e.WaitStepState(t, a.ns, pipelineName, bundle, "prod", "Verified", promoteTimeout)
	assertEnvAt(t, a, "prod", fixtures.V2)
}

// TestSCM_WebhookMergeIsConfirmed posts a merge event, signed with the
// webhook secret, for a PR that is still open. The controller asks the git
// server whether the PR is merged, so the PRStatus is not marked merged and
// the step keeps waiting; any validly signed merge event used to advance the
// step without a merge (B73). The same event signed wrong, and unsigned, is
// refused and logged with the header its signature was read from and the
// sender's address (B76). Once the PR is merged, the event is confirmed and
// marks it merged, logged with its repo and the PRStatus namespace.
//
// Covers WEBHOOK-CONFIRM-01, WEBHOOK-LOG-01.
func TestSCM_WebhookMergeIsConfirmed(t *testing.T) {
	t.Parallel()
	e := framework.New(t)
	a, bundle, pr, prs := prOpenWithoutWebhook(t, e)
	kind := e.Git.Kind()
	sig := kindSignature(kind)
	body := mergedEvent(t, kind, prs.Spec.Repo, pr.Number, pr.HeadSHA)
	since := time.Now()
	require.Equal(t, http.StatusNoContent, e.PostSCMWebhook(t, signedPREvent(sig, framework.WebhookSecret(t), body), body),
		"the merge event of the open PR, signed in %s", sig)
	e.WaitControllerLog(t, since, 30*time.Second, "the git server reporting PR #"+strconv.Itoa(pr.Number)+" open",
		framework.LogMessage("SCM provider reports the PR of the merge event not merged; PRStatus not marked merged",
			"prstatus", prs.Name, "namespace", a.ns, "repo", prs.Spec.Repo, "pr", strconv.Itoa(pr.Number), "open", "true"))
	a.stillOpen(t, bundle, "prod", 15*time.Second, "after the merge event of the open PR")
	assert.Empty(t, e.ControllerLogLines(t, since, framework.LogMessage("PRStatus marked merged via webhook", "prstatus", prs.Name)))

	for _, c := range []struct {
		header, logged string
		headers        map[string]string
	}{
		{sig, sig, signedPREvent(sig, "not-the-secret", body)},
		{"no signature", "none", map[string]string{eventHeader(sig): prEvent(sig)}},
	} {
		since := time.Now()
		require.Equal(t, http.StatusUnauthorized, e.PostSCMWebhook(t, c.headers, body), "the merge event, %s", c.header)
		l := e.WaitControllerLog(t, since, 30*time.Second, "the refused event logged with signatureHeader "+c.logged,
			framework.LogMessage("webhook signature invalid or parse error", "signatureHeader", c.logged))
		assert.NotEmpty(t, l.Str("remoteAddr"), "the sender of the refused event: %s", l)
	}

	// Signed right once the PR is merged, the event is confirmed and marks
	// the PRStatus merged (mergeSeenByWebhook checks the logged repo and
	// namespace).
	a.mergeByWebhook(t, bundle, "prod", sig, true)
	assertEnvAt(t, a, "prod", fixtures.V2)
}

// TestSCM_DuplicatePRReusesSameBase checks which PR open-pr adopts when the
// git server refuses a duplicate: with the promotion PR open and a second PR
// from the same branch into another base, a rerun of open-pr finds the PR
// into the Pipeline's branch and never the other one, and opens nothing new.
//
// Covers SCM-OTHERBASE-01.
func TestSCM_DuplicatePRReusesSameBase(t *testing.T) {
	t.Parallel()
	e := framework.New(t)
	a := newArgoApp(t, e, "prod")
	a.apply(t, a.pipeline(map[string]string{"prod": "pr-review"}))
	bundle := e.CreateBundle(t, a.ns, pipelineName, "--image", imageV2)
	ps, pr := a.waitOpenPR(t, bundle, "prod")

	other := a.repo
	other.Branch = a.repo.Branch + "-other"
	e.GitBranch(t, a.repo, other.Branch, a.repo.Branch)
	ctx := context.Background()
	stray, err := e.Brancher(t).OpenPR(ctx, a.repo, pr.Head, other.Branch, "e2e: the same head into another base")
	require.NoError(t, err)
	t.Cleanup(func() { _ = e.Git.ClosePR(context.Background(), other, stray.Number) })
	t.Logf("PR #%d from %s into %s", stray.Number, pr.Head, other.Branch)

	ps = a.rerunOpenPR(t, ps, bundle, "prod")
	assert.Equal(t, strconv.Itoa(pr.Number), ps.Status.Outputs["prNumber"],
		"open-pr adopts PR #%d into %s, not #%d into %s", pr.Number, a.repo.Branch, stray.Number, other.Branch)
	assert.True(t, strings.HasSuffix(ps.Status.PRURL, "/"+strconv.Itoa(pr.Number)), "prURL %s", ps.Status.PRURL)

	prs, err := e.Git.PullRequests(ctx, a.repo)
	require.NoError(t, err)
	var into []string
	for _, p := range prs {
		if p.Head == pr.Head {
			into = append(into, fmt.Sprintf("#%d %s", p.Number, p.State))
		}
	}
	assert.Equal(t, []string{fmt.Sprintf("#%d open", pr.Number)}, into, "PRs from %s into %s", pr.Head, a.repo.Branch)
	prs, err = e.Git.PullRequests(ctx, other)
	require.NoError(t, err)
	var stays []string
	for _, p := range prs {
		stays = append(stays, fmt.Sprintf("#%d %s", p.Number, p.State))
	}
	assert.Equal(t, []string{fmt.Sprintf("#%d open", stray.Number)}, stays, "PRs into %s", other.Branch)

	require.NoError(t, e.Git.ClosePR(ctx, other, stray.Number))
	a.merge(t, pr)
	e.WaitStepState(t, a.ns, pipelineName, bundle, "prod", "Verified", promoteTimeout)
	assertEnvAt(t, a, "prod", fixtures.V2)
}

// TestSCM_KardinalClosedPRGetsOneComment: a prod PR not merged within
// waitForMergeTimeout is closed by kardinal, with one comment saying why. Its
// Bundle fails and keeps its Graph, so the PRStatus keeps polling the closed
// PR. When the 5-minute grace window ends, the PRStatus reconciler used to
// post a second comment, "kardinal stopped tracking this PR", which is meant
// for a PR a person closed (#1351). The close marks the PRStatus with the PR
// number (kardinal.io/closed-by-kardinal), so the PR keeps its one comment
// after the window: the PRStatus is final-closed and has no second comment.
//
// Covers SCM-CLOSED-02.
func TestSCM_KardinalClosedPRGetsOneComment(t *testing.T) {
	t.Parallel()
	e := framework.New(t)
	a := newArgoApp(t, e, "prod")
	p := a.pipeline(map[string]string{"prod": "pr-review"})
	envSpec(t, p, "prod").WaitForMergeTimeout = "60s"
	a.apply(t, p)

	bundle := e.CreateBundle(t, a.ns, pipelineName, "--image", imageV2)
	_, pr := a.waitOpenPR(t, bundle, "prod")
	ps := e.WaitStepState(t, a.ns, pipelineName, bundle, "prod", "Failed", 3*time.Minute)
	assert.Contains(t, ps.Status.Message, "wait-for-merge timeout after 1m0s")
	e.WaitPRState(t, a.repo, pr.Number, "closed", time.Minute)
	oneComment(t, a, pr.Number, "kardinal closed this PR: it was not merged within waitForMergeTimeout (1m0s)")

	prs := e.WaitPRStatus(t, a.ns, pipelineName, bundle, "prod", closedGrace+2*time.Minute,
		"the PRStatus final-closed after the grace window", func(p *v1alpha1.PRStatus) bool {
			return p.Spec.PRNumber == pr.Number && p.Status.ClosedFinal
		})
	assert.Equal(t, strconv.Itoa(pr.Number), prs.Annotations["kardinal.io/closed-by-kardinal"],
		"the close marked the PRStatus with the PR number")
	framework.Consistently(t, 20*time.Second, "no stopped-tracking comment on the PR kardinal closed", func(context.Context) (bool, string) {
		n := len(e.PRComments(t, a.repo, pr.Number, "kardinal stopped tracking this PR"))
		return n == 0, fmt.Sprintf("%d stopped-tracking comments", n)
	})
	assert.Len(t, e.PRComments(t, a.repo, pr.Number, "kardinal closed this PR"), 1, "PR #%d keeps its one close comment", pr.Number)
	assertEnvAt(t, a, "prod", fixtures.V1)
}
